### ISSUE TITLE
Home Page photo resizing at different window sizes

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#100]
As one changes window sizes from large to small, the size of home page photos changes, until you get to where it switches to 2 photos, then eventually 1 photo on mobile devices.  The resizing is done in a way that crops the image in an undesirable way.   First picture below is with a wide screen, the second with a narrower screen (my laptop).  Notice the third picture, how it shifts vertically:

![Screen Shot 2020-02-17 at 3 46 59 PM](https://user-images.githubusercontent.com/12800484/74685625-13ac5d80-519d-11ea-85c9-5eb5947b856f.png)

<img width="1205" alt="Screen Shot 2020-02-17 at 3 50 25 PM" src="https://user-images.githubusercontent.com/12800484/74685708-49e9dd00-519d-11ea-8950-9b89b5d15096.png">

Suggestion is to keep the vertical size full size, and only have the pictures take up the width of the screen that they take up, leaving space on the left and right.  That is how the buttons work and then the pictures show what they intend to show, no guesswork needed.

**Comment by kaatvds** [comment]
same comment here as for #101

**Comment by kaatvds** [comment]
Date works, looks good! However, when an event is community-wide it would be great to put in only the town and no street address and unit #. When  not it says "null" on the card.
![image](https://user-images.githubusercontent.com/30277868/82740469-fa282e00-9d16-11ea-908e-02a3964f9776.png)
