### ISSUE TITLE
Sign-in with Google - doesn't let me choose my profile

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#1015]
### Describe the bug
When I sign in to the community portal, I use sign-in with Google and I'd like to choose between my standard user profile, my cadmin profile or my sadmin-profile.  Even if I use an incognito window, it remembers which profile I used most recently and instead of showing me the dialog to choose which Google profile to use, it skips that and signs in.

### To Reproduce
1. Go to community portal sign-in page
2. Choose signin with profile
3. Click on the Google icon

### Expected behavior
You should see a dialog with your google profiles that have been used before

### Desktop (please complete the following information):
 - OS: Macos
 - Browser Chrome or Safari
 - Version any

### Additional context
Maybe also a problem on mobile, probably is.

**Comment by abdullai-t** [comment]
I think this issue is not from our platform
