### ISSUE TITLE
Friction on changing passwords - provide link to sign in page

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#1016]
### User Story
As a **User**. (Actor/User)
I want **change my password and get a link right back to the platform**. (Goal of the actor/user)
So that **I don't have to find the tab I used beforre**. (Why/What is the result)

### Additional details/context
I forgot my password, got the email and changed my passord. Then arrived at the following screen:
<img width="443" alt="Screen Shot 2022-05-19 at 7 57 14 PM" src="https://user-images.githubusercontent.com/12800484/169423092-1740208b-8f76-422e-aa80-c3452c749780.png">

### Value added
Make it easier to sgn in

### Acceptance criteria
You need a link to the home page, having signed in with the new password.

**Comment by Davidjwkinghorn** [comment]
Maybe we can redirect to sign in page on password changed and email confirmation.
