### ISSUE TITLE
[Bug] Guest user can start a team, but can't join one.

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#1023]
### Describe the bug
Disallow guests from creating teams.

### Screenshots or video
<img width="1227" alt="Screen Shot 2022-05-27 at 8 36 43 AM" src="https://user-images.githubusercontent.com/12800484/170700476-8bcf60b9-a8de-46e7-91ea-09716fd3e77b.png">

**Comment by abdullai-t** [comment]
@BradHN1  and @Davidjwkinghorn  should guest users be able to join teams ?
