### ISSUE TITLE
[Bug] RECAPTCHA SITE KEY BROKE - prevents users creating profile

### ISSUE THREAD

**Issue by apowelka** [massenergize/frontend-portal#1035]
A user is trying to create a profile but cannot because the recaptcha is not working. Error message is "ERROR for the site owner: Invalid domain for site key"

![image](https://user-images.githubusercontent.com/60662056/172412857-8b58c2d1-b009-4be8-9159-3b93ca0eced3.png)

**Comment by BradHN1** [comment]
@dave - this is because Google recaptcha checks the domain against whitelisted domains, and energizeframingham.org wasn’t on there.  I just added it, and this ticket can be closed.  There is another ticket for eliminating the need to set the recatpcha whitelisted domains.
