### ISSUE TITLE
Remove paypal button to MassEnergize on DONATE page

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#1052]
Most organizers wants this removed.

**Comment by abdullai-t** [comment]
@kaatvds what is the status of this ticket ?

**Comment by kaatvds** [comment]
Hi Tahiru, I was asking @Davidjwkinghorn or @Brad to assign it a status (sprint backlog, priority, etc). So no status yet :)

**Comment by abdullai-t** [comment]
Does mean that there wouldn't be any donate button?

**Comment by abdullai-t** [comment]
##Current page
<img width="1317" alt="Screenshot 2022-07-29 at 9 34 01 PM" src="https://user-images.githubusercontent.com/42780120/181846033-ceefee5a-fa97-4e29-9375-aead9e0f53a7.png">

## After removing paypal button
<img width="1180" alt="Screenshot 2022-07-29 at 9 33 42 PM" src="https://user-images.githubusercontent.com/42780120/181846201-89f7efb9-1d51-4824-97ae-f0a6599c1f09.png">

@kaatvds is this☝🏻 the change we want ?

**Comment by kaatvds** [comment]
Yes please :)
