### ISSUE TITLE
[Feature] Improve the profile editing and setting access

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#1088]
The access to editing ones profile and communications options can e improved.
In particular the caret pulldown on the Profile page may not be obvious enough

Need to clarify requirements.

### User Story
As a **_______**. (Actor/User)
I want **______**. (Goal of the actor/user)
So that **______**. (Why/What is the result)

### Additional details/context
Add any other details, context, UI mockups, examples from other products, or anything else that might help the developers know what to make.

### Value added
What do you think the value of adding this feature is? Help managers and developers know how this should be prioritized.

### Acceptance criteria
The conditions that must be met for this to be done. For example, for a login feature: User is securely and reliably logged in until timeout or manual sign-out.

**Comment by kaatvds** [comment]
Put all those options under the caret under "Preferences" (in dropdown under profile pic). (Now called "Settings" in dev)
Next to the name in the profile add text "Change my preferences" that links to the Preferences page.
