### ISSUE TITLE
Testimonials in Actions tab formatting

### ISSUE THREAD

**Issue by apowelka** [massenergize/frontend-portal#109]
Hi - the testimonials show up on the action tab, which is great, but the formatting is all messed up. The name of the contributor is huge and first and the title is tiny and second. these should be swapped so that the formatting looks like the testimonials format on the testimonials page.
(should this be separate? : Also, the testimonials in the separate testimonials page do not display the name or date)

![2020-02-27 Test_Format_Wrong_in_ActionTab](https://user-images.githubusercontent.com/60662056/75457962-1cdebc80-594b-11ea-860f-7cdcbb56bc13.png)
![2020-02-27 Testimonial_FormatGood_NoName](https://user-images.githubusercontent.com/60662056/75458148-6202ee80-594b-11ea-9026-93273be371a0.png)

**Comment by kaatvds** [comment]
making a separate tickets for "Also, the testimonials in the separate testimonials page do not display the name or date"
