### ISSUE TITLE
[Bug] User settings page is blank

### ISSUE THREAD

**Issue by Davidjwkinghorn** [massenergize/frontend-portal#1098]
### Describe the bug
User profile settings is an option, but takes you to a blank page. We should hide this behind a feature flag until it's fixed and we're ready to roll it out.

### Screenshots or video
![Screen Shot 2022-08-15 at 3 27 33 PM](https://user-images.githubusercontent.com/15150372/184703576-1b0dd82f-99b2-4c5a-88f9-b39c26017dd9.png)

**Comment by frimpongopoku** [comment]
@abdullai-t  I was able to intercept this, and it looks like its from the backend.
Here....
`"Invalid response to settings.list Data: {"__is_prod":true,"__community":"ConcordMA","__is_sandbox":false,"subdomain":"ConcordMA"}"`



![Image](https://user-images.githubusercontent.com/26961591/184789695-8fe9e327-717b-4d91-8c71-5cfb3295536a.png)

But to be safe in future, hook the fronted up with something like this 🤣 🤣 

![Image](https://user-images.githubusercontent.com/26961591/184789973-cb85aa3e-777b-4dcc-a77c-50483faf7993.png)
