### ISSUE TITLE
Make vendors rich text

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#111]
For individual vendor pages we need rich text in order to put in links to their websites, etc.

**Comment by kaatvds** [comment]
I don't see rich text ???

**Comment by kaatvds** [comment]
open because rich text doesn't come through:
![image](https://user-images.githubusercontent.com/30277868/79752443-50521d80-82e2-11ea-8bfd-0cfecf3de424.png)

**Comment by massenergize-admin** [comment]
Yeah this means my part is done.  Frimpong as to do his thing to render the rich text.  the jibberish you see there is the rich text
