### ISSUE TITLE
formatting on popup/page that you were sent an email

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#1115]
When i created a new account and get the page tell ing me I was sent an email, 
if the screen is set to be large (zoomed in)
the "Not there" sentence is stuck to the end of the "Promotions folders" sentence without a spacing and the interlining is off
<img width="867" alt="Screen Shot 2022-09-07 at 2 41 39 PM" src="https://user-images.githubusercontent.com/30277868/188954112-5adab629-d4b0-4916-b472-d98f4b1c67b7.png">

**Comment by abdullai-t** [comment]
This issue is fixed

<img width="1680" alt="Screenshot 2023-03-29 at 9 12 09 AM" src="https://user-images.githubusercontent.com/42780120/228485933-b6d3a3e5-b82d-4ef1-b37a-b99b882b7153.png">
