### ISSUE TITLE
on Contact us page, Send message button doesn't SEEM to work

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#1119]
on Contact us page, Send message button doesn't SEEM to work. it does and the message IS sent, but there is no indication of success to the user.

### Screenshots or video
If applicable, add screenshots or video to help explain your problem.

**Comment by abdullai-t** [comment]
I fixed that in this [PR](https://github.com/massenergize/api/pull/599)

**Comment by Davidjwkinghorn** [comment]
I think this ticket has to do with UI feedback on the front end, separate from your fix to messages breaking in the back end.

**Comment by frimpongopoku** [comment]
@Davidjwkinghorn  they are related. The api-end bugs tahiru fixed are what was blocking the form from receiving positive response in order for it to show a success message. 

Also, @abdullai-t before you fix a ticket, check with who is assigned before? And in tricky situations like this, it still helps to notify them if you fixed them by chance 🤣. 

I also went to fix the contact us form, but from a frontend perspective 🌚

**Comment by abdullai-t** [comment]
noted @frimpongopoku

**Comment by Davidjwkinghorn** [comment]
> @Davidjwkinghorn they are related. The api-end bugs tahiru fixed are what was blocking the form from receiving positive response in order for it to show a success message.

Tahiru, was actually fixing another separate ticket that may have also related to this issue.
