### ISSUE TITLE
[Change]  In Full view of Testimonials: Display full image for thumbnails, don't crop.

### ISSUE THREAD

**Issue by Davidjwkinghorn** [massenergize/frontend-portal#1120]
### Additional details/context
It's okay if some images have space around them, if they're not square, but cutting off images that have weird width/height ratios can cause some problems. 😅

![image](https://user-images.githubusercontent.com/15150372/192405864-953bdcc7-1f75-4723-9f59-f9dd3dcbb68d.png)

**Comment by kaatvds** [comment]
This is only a problem for the "related to action" display on a testimonail (when opened to full view): the image there should not be cropped. Action images are usually wider than 1:1 whcih is the crop used here.
