### ISSUE TITLE
Shared events do not display in date order

### ISSUE THREAD

**Issue by apowelka** [massenergize/frontend-portal#1143]
Shared events are displayed in the order that they were shared rather than in order by date. Because there is no way to un-share (currently), this should be considered a bug.

**Comment by BradHN1** [comment]
I've implemented changes which accomplish what is called for here.  See the video for details: 

https://user-images.githubusercontent.com/12800484/212158143-040f7738-ebdb-492a-b78a-21257c61620c.mov

Two new tabs (past events, and campaigns (for now, events which last more than 7 days)) switch between upcoming events, past events and campaigns.  Upcoming events are sorted by date in forwards order; past events are sorted by date in reverse order (recent first), campaigns are sorted in forwards order by start date.

The home page will now show upcoming events and campaigns, ordered by start date. So Campaigns may show up first though you can control that with the start date.

Note: this now doesn't use Rank for anything, so currently event Rank serves no purpose.  I can't think of a way to use Rank partly and Date partly, and in my mind Date should be good enough.  For campaigns you need to set the end date to be in the future, and the start date controls the order the campaign will be listed.
