### ISSUE TITLE
[Bug] Feature flags not working properly on Community Portal

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#1152]
### Describe the bug
On the Prod community portal, we have set a feature flag for guest_authentication, which is set to be enabled for Energize Lexington and Energize Wayland.  But the guest_authentication is visible on other community sites including Cooler Concord.

**Comment by abdullai-t** [comment]
@BradHN1 - I tested this in canary and the guest auth was showing for all communities. I was able to limit it to only Wayland and Concord by changing the `Community Audience` of the feature flag's form on the admin portal to `specific` and selecting Wayland and concord in the list of communities provided. I think this could  fix the issue in prod
