### ISSUE TITLE
Display on iphone cuts off logo and too much white space

### ISSUE THREAD

**Issue by ellentohn** [massenergize/frontend-portal#116]
1. When I access energizewayland.org on my iphone 6, the logo is cut off on the top. 
2. One the iphone we see too much white space below the tag line, before we see the Get Started - See Your Local Options  -- can we remove white space
3. Boxes (Actions, Events, Service Providers, Testimonials )  --- can these be smallers its a lot of scrolling and users have given us feedback that this gets frustrating 
![Mass Energize home on iphone](https://user-images.githubusercontent.com/60329553/75640536-65c09a80-5c03-11ea-9392-e4bfd4353084.png)
![Mass Energize user profile logo cut off](https://user-images.githubusercontent.com/60329553/75640538-678a5e00-5c03-11ea-8d34-15bdea249705.png)

**Comment by kaatvds** [comment]
The logo on top is still cut off - not as much as before. If this is best solved by logos following a strict size, let us know that size.

**Comment by ellentohn** [comment]
Logo looks good on iphone; not on motorola, Kaat wil provide a screen shot

**Comment by ellentohn** [comment]
white space is fine after tag line and before boxes, BUT please reduce white space above -- Help us Reach Our Goa  AND Above Upcoming Events and Campaigns

**Comment by kaatvds** [comment]
Boxes (Actions, Events, Service Providers, Testimonials ) have to be smaller
Between last box "testimonials" and "help us reach our goal" too much white space
