### ISSUE TITLE
Phone Display - testimonials image cuts off text

### ISSUE THREAD

**Issue by ellentohn** [massenergize/frontend-portal#118]
See below screen shot. when the user clicks on ..more to read a full testimonials the image cuts off the text and it only takes up half the screen.

Can we fix the image so it does not cut off the text and also maybe use more of the full screen to show the text. 

![Mass Energizetestimonials ](https://user-images.githubusercontent.com/60329553/75746303-dfca4f80-5ce7-11ea-93af-61d1a72c5918.png)

**Comment by kaatvds** [comment]
Indiv testimonial (after clicking more) text is too close (almost cut off) to right side by scrolling bar. Trying to take a screenshot...

**Comment by kaatvds** [comment]
has something to do with two scroll bars on motorola

**Comment by kaatvds** [comment]
woks fine on iphone

**Comment by kaatvds** [comment]
still happens, Ellen's phone:
 
![IMG_0284](https://user-images.githubusercontent.com/30277868/77179150-75aefa00-6a9e-11ea-8ef0-6d4ca6d26917.jpeg)
