### ISSUE TITLE
Actions filter bar should stay one line tall, including the search field

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#1188]
The filter bar on All Actions (Events, Vendors, Testimonials, etc) should take minimal vertical space, and if possible stay one line tall on a laptop view.  If the items on the bar overflow horizontally, you should be able to scroll left and right to set them, maybe with an indicator (like "More>>" ) to show there is more stuff hidden.

<img width="963" alt="Screenshot 2023-04-21 at 11 50 20 AM" src="https://user-images.githubusercontent.com/12800484/233681557-7d77998f-75a5-414a-8f92-9606d1f3ec56.png">
<img width="983" alt="Screenshot 2023-04-21 at 11 51 22 AM" src="https://user-images.githubusercontent.com/12800484/233681560-5a6b724f-055a-41a6-81e3-197dc726d655.png">
<img width="931" alt="Screenshot 2023-04-21 at 11 57 56 AM" src="https://user-images.githubusercontent.com/12800484/233681814-40a86240-75b3-412c-b6b5-ccbf64d3d33b.png">

**Comment by abdullai-t** [comment]
@BradHN1, Making it overflow horizontally will cause chaos in the dropdown contents.

**Comment by BradHN1** [comment]
I'm not sure what 'chaos' means, but we want the filter/search bar to be one line tall.  If there are too many tag collections, those should be able to scroll horizontally.

**Comment by BradHN1** [comment]
Discussed the button to add content with Kaat and Aimee, and we would prefer to leave it in the filter bar.  
We should discuss whether the Filers and this button can be swiped horizontally to have everything fit in one line.

**Comment by abdullai-t** [comment]
https://user-images.githubusercontent.com/42780120/236185399-641cb4c3-2252-4406-be47-777f771ead6d.mp4
