### ISSUE TITLE
Guest / email only user registration appears to be broken

### ISSUE THREAD

**Issue by apowelka** [massenergize/frontend-portal#1194]
I tried to create an email only log-in. 

1. Got an authentification email but it took about 30 seconds longer than it should have.

2. BUG: After completing fields for name, user name and zip, I CANNOT click "Finish Signing Up."
Error message: Invalid domain for site key

Kaat says maybe our captcha expired?

![IMG_4430](https://user-images.githubusercontent.com/60662056/236030189-0259f917-0a50-4a34-a7dd-0ded9e79884e.jpg)

**Comment by abdullai-t** [comment]
Hello, @apowelka. Based on my testing, it seems that the email-only registration feature is functioning properly across all platforms. However, I would like to clarify whether this issue occurred on a custom website. If it did, could you please provide me with the name or URL of the website? This will allow me to investigate the matter further. Thank you.

**Comment by BradHN1** [comment]
This bug has been fixed.  The domain energizeframingham.org <http://energizeframingham.org/> needed to be added to the Google Recaptcha list.
