### ISSUE TITLE
Phone display - our impact 

### ISSUE THREAD

**Issue by ellentohn** [massenergize/frontend-portal#122]
It is a bit difficult to read the graph for our impact. Could we possibly make it bigger?

![phone our impact ](https://user-images.githubusercontent.com/60329553/75746687-0b016e80-5ce9-11ea-80e4-a42c3a9f0ecb.png)

**Comment by kaatvds** [comment]
it looks worse on  my phone (motorala): 
![Screenshot_20200327-135020](https://user-images.githubusercontent.com/30277868/77785148-29c9fb00-7032-11ea-9cc7-ace15f351b08.png)
![Screenshot_20200327-135029](https://user-images.githubusercontent.com/30277868/77785157-2c2c5500-7032-11ea-92fa-41a47d8d783e.png)

**Comment by kaatvds** [comment]
activism
home energy
solar
food
waste
transit

**Comment by BradHN1** [comment]
Testing @ellentohn @OrlyStrobel

**Comment by OrlyStrobel** [comment]
This looks good to me, but I am not 100% clear on how big everyone else wants it to be so I will let others test it before moving it to validated in QA @BradHN1 @ellentohn

**Comment by jkatofsky** [comment]
I hope this is the right place for this; on widow widths that are small enough for the graphs to stack vertically, but wider than mobile, the circle graphs overflow their divs. 
![image](https://user-images.githubusercontent.com/13226824/85068184-fc4ba400-b17f-11ea-808d-17b80ac6294c.png)

**Comment by BradHN1** [comment]
Deployed to Dev
Testing: @OrlyStrobel @kaatvds @ellentohn

**Comment by OrlyStrobel** [comment]
How, looks much better!

**Comment by OrlyStrobel** [comment]
Looks good on prod on mobile.
