### ISSUE TITLE
formatting  on all actions  page - and extra space on other All... pages

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#1220]
on all Actions page a couple of things:

On All Actions When one narrows the screen the To DO and DoNE boxes overlap.
When the screen is too narrow the content on cards becomes smaller and the cards too wider. 

Both these can be see on the screenshot:
<img width="771" alt="Screenshot 2023-06-21 at 2 05 38 PM" src="https://github.com/massenergize/frontend-portal/assets/30277868/ff9e35fa-050a-404b-8b83-a6ec5b1a6fd2">

Also int hat screenshot AND on other "All..." pages : too much space between the filter and the cards or tabs: eliminate al that white space.

**Comment by abdullai-t** [comment]
@kaatvds and @BradHN1, I will need you inputs on the demo below

https://github.com/massenergize/frontend-portal/assets/42780120/fb99c4ee-773c-4f5f-86da-eaa7a7678619

**Comment by BradHN1** [comment]
That is pretty good, but on the mobile view the green bar at the bottom should be fixed.  The idea is when you record an action you can see that adding to the impact number right there.  Not needing to scroll to it.

**Comment by kaatvds** [comment]
My concern is not so much with different "screens" (all at 100% as in your demo) but with the same screen, like a laptop, and then people 
- either resizing their browser zoom. Some prefer 120% and some like 80%, 
- or making their browser narrower in order to have two views on one screen. 
Both mess up the responsiveness too.  Cf video below
Can you try the same maneuvers as in the video with your laptop screen and see how it behaves?

https://github.com/massenergize/frontend-portal/assets/30277868/b281b9dd-cd69-4551-a523-faaa8f991139

**Comment by abdullai-t** [comment]
> is pretty good, but on the mobile view the green bar at the bottom should b

@kaatvds, the incoming changes will make it look good on those zoom levels and more.

https://github.com/massenergize/frontend-portal/assets/42780120/1dc6c6ea-1b09-4da0-b042-12391aa9c347

**Comment by kaatvds** [comment]
Great. Will this be in dev or can first?

**Comment by abdullai-t** [comment]
it will be in dev first. @BradHN1 can also push to can for you to test
