### ISSUE TITLE
Download calendar entry for event (ics)

### ISSUE THREAD

**Issue by apowelka** [massenergize/frontend-portal#1234]
As a user, I want to quickly add an event on the energize site to my personal calendar. So that i don't have to type it in.

add ability to download an ics file so that the user can add it to their calendar. 

Add this below the date on the single event page with buttons like in the following example

like this
![image](https://github.com/massenergize/frontend-portal/assets/60662056/8bbf13f5-084d-46c7-8c33-2ef31a815ed5)

(you can see that example here: https://www.livingconcord.com/event/july-4th-picnic-in-the-park-3/

There may be better examples on other sites you could look at.

**Comment by BradHN1** [comment]
The ICS file downloaded should have the address and/or join link in the location field,
the short event summary and link back to the event page on the user portal in the details, like in this example:


![Image](https://github.com/massenergize/frontend-portal/assets/12800484/8166bbfb-cfd4-4f54-92ea-7c171fa5c681)

**Comment by BradHN1** [comment]
In the example above, there is also a "Add to google calendar"; this would also be useful if you can do it.
That button links to: https://www.google.com/calendar/event?action=TEMPLATE&text=July+4th+Picnic+in+the+Park&dates=20230704T110000/20230704T163000&details=Food%2C+Games%2C+Live+Entertainment+%0AFamily+Fun+for+All%21+%0A&location=Emerson+Field%2C+United+States&trp=false&sprop=website:https://www.livingconcord.com&ctz=America%2FNew_York

**Comment by BradHN1** [comment]
@abdullai-t - In testing this, the ICS file downloaded has the full event text, which is not what we want.

The ICS file downloaded should have the the short event summary and link back to the event page on the user portal in the details, like in this example:

**Comment by BradHN1** [comment]
Also - above the two buttons, can you add "Download to your calendar:" in green font same spacing as the headings like Venue above it.
