### ISSUE TITLE
Improve email verification template from Firebase

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#1237]
The user authentication flow for the MassEnergize site using email only is a problem, because it does not come from the community site, but from the MassEnergize Community Platform which the user has probably not heard of:

![Screenshot 2023-07-13 at 7 01 01 PM](https://github.com/massenergize/frontend-portal/assets/12800484/da57b4b8-08dd-4316-a4e4-48e1825d35fe)

Firebase itself does not offer the option of customizing this template.  However it is possible to do it as described in this Stackoverflow entry:

https://stackoverflow.com/questions/50075602/firebase-authentication-email-customisation

Here is info on setting up an email handler: https://firebase.google.com/docs/auth/custom-email-handler
Perhaps this should be a route within the API

**Comment by BradHN1** [comment]
Assuming we can customize the template, it needs to come from the community:  like "Energize Lexington" and have the logo included

**Comment by abdullai-t** [comment]
@BradHN1, I couldn't customise the template on firebase but I was able to redirect the process to the backend. So now the processing of the verification link is done at the backend. Also, we are using postmark to send the emails. This is how the template looks now:
<img width="807" alt="Screenshot 2023-07-22 at 9 28 35 PM" src="https://github.com/massenergize/frontend-portal/assets/42780120/33baa91b-b862-4315-8258-f266503a6cc7">

**Comment by BradHN1** [comment]
@abdullai-t - this is better than before, but I edited the template to add the community logo, and pushed it to the other servers.
Also - this should also be done for someone who signs up with email and password.  Can you make that change?

**Comment by abdullai-t** [comment]
yes I can.
