### ISSUE TITLE
Easier event address reading

### ISSUE THREAD

**Issue by apowelka** [massenergize/frontend-portal#1256]
As a user, I want to quickly look at an event's address and know where to go.

Each field of the address should be a separate line. Right now, it all runs on together.

![image](https://github.com/massenergize/frontend-portal/assets/60662056/61f72578-65ca-4014-954b-b58fbc77b06c)

I'd like:
Framingham Main Library
Costin Room
49 Lexington St.
Framingham, MA

Accompanying CAdmin ticket #1077.

**Comment by abdullai-t** [comment]
@apowelka, is this what you meant ?
<img width="1410" alt="Screenshot 2023-08-29 at 11 36 33 AM" src="https://github.com/massenergize/frontend-portal/assets/42780120/47a322ed-98e2-41d8-ae43-757a0aae071c">

**Comment by apowelka** [comment]
yes, this is perfect! Thank you!
