### ISSUE TITLE
Phone - my actions link broken 

### ISSUE THREAD

**Issue by apowelka** [massenergize/frontend-portal#126]
On my iPhone, I tried clicking on the actions in my to do list as and in my done list. Both went to a broken link page. Shouldn’t they go to the action itself?
![AD7F501A-78AA-424C-A3F4-A5CFF785FE64](https://user-images.githubusercontent.com/60662056/76017323-69e30580-5eec-11ea-8c12-3545b40cb023.png)

**Comment by kaatvds** [comment]
Aimee can you test this again?

**Comment by apowelka** [comment]
Tested and seems fixed! Yeah!

**Comment by apowelka** [comment]
tested it, it seems fixed - yeah! Nice work team
