### ISSUE TITLE
Phone Display: Actions/Buttons/Done it

### ISSUE THREAD

**Issue by ellentohn** [massenergize/frontend-portal#127]
On my iphone 6, the buttons for More Ino and Add to to Do are the same size. However the Done it button is smaller. Can we make the green buttons all the same size. so Done it needs to be bigger 
![button size](https://user-images.githubusercontent.com/60329553/76094712-11b20f00-5f91-11ea-870b-52dcf7369643.png)

**Comment by kaatvds** [comment]
This still happens. Ellen's screenshots:
![Mass Energize](https://user-images.githubusercontent.com/30277868/77337719-a5a90800-6cff-11ea-8b6f-7d165f7e8c85.png)
![Mass Energize (1)](https://user-images.githubusercontent.com/30277868/77337723-a80b6200-6cff-11ea-902e-54cfea2b6215.png)

**Comment by ellentohn** [comment]
just tested this and the middle button is larger than the others. see attachments, I have an iphone 6 
![image](https://user-images.githubusercontent.com/60329553/77337929-ff113700-6cff-11ea-91c6-3be433f0b4c5.png)
![Mass Energize button size middle too big](https://user-images.githubusercontent.com/60329553/77338000-14866100-6d00-11ea-9f02-050adf416cac.png)
![Mass Energize middle button big food](https://user-images.githubusercontent.com/60329553/77338002-151ef780-6d00-11ea-9a3f-dbf3f3ee6e41.png)

**Comment by ellentohn** [comment]
it looks like the text "add to do" is wrapping and that is making the button big

**Comment by ellentohn** [comment]
The button is the correct size 'add to do" -- when it is grey but its still big when it is green

**Comment by ellentohn** [comment]
See here 
![Mass Energize button size ok grey ok 3 23 20](https://user-images.githubusercontent.com/60329553/77338792-37fddb80-6d01-11ea-8715-57ac7e7e8ca3.png)

**Comment by ellentohn** [comment]
3.26.20 the middle "Add to Do" button is still not the same size as the others -- it is still too big, on the iphone 6, it looks fine on the samsung,.. see below
![Mass Energize button size middle too big](https://user-images.githubusercontent.com/60329553/77777356-d651b000-7025-11ea-828f-c70f446771f9.png)

**Comment by ellentohn** [comment]
I am still seeing an issue; when I go to all actions; click on an action and then click More info; its the next screen after clicking more info where the buttons are not in a row 
![#127 Actions; buttons not aligned after clicking more info](https://user-images.githubusercontent.com/60329553/79017407-3c1e5b80-7b3f-11ea-8487-a16f2bc91b5d.png)
![#127 Actions; buttons not aligned](https://user-images.githubusercontent.com/60329553/79017410-3cb6f200-7b3f-11ea-9e80-6a81d0bc3822.PNG)

I tested this on Dev
