### ISSUE TITLE
Crash on single action page if you sign out

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#1273]
### Describe the bug
I was on a single action page: coolerconcord.org/actions/1384, and signed out o fht eplatform.

Got a white screen.

Errors in console:
<img width="587" alt="Screenshot 2023-11-07 at 12 52 45 PM" src="https://github.com/massenergize/frontend-portal/assets/12800484/bfaf3d1d-21e6-4c98-a433-1107bbada5af">

Reloading the page clears the error.

**Comment by frimpongopoku** [comment]
The issue is fixed
