### ISSUE TITLE
Deployment routine for frontend User Portal

### ISSUE THREAD

**Issue by archx3** [massenergize/frontend-portal#1300]
### **Possible Scenarios**

**SCENARIO 1.**

### **Required Permissions**
Any user with confirmed access to the profile page being viewed.

**Acceptance Criteria**

- [ ] 

###### UX Design
Insert figma link or link to design

###### Technical Considerations
Insert technical considerations

**Comment by BradHN1** [comment]
Not much information in this ticket.
