### ISSUE TITLE
on phone testimonials: two scroll bars one next to the other

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#131]
on phone, testimonials text seems to have two scroll bars one next to the other.

**Comment by kaatvds** [comment]
this is also the case on testimonials on DEV but weirdly not in Prod...
![image](https://user-images.githubusercontent.com/30277868/76101034-bafe0280-5f9b-11ea-8d40-607550d62408.png)

**Comment by kaatvds** [comment]
still an issue. also on my laptop.

**Comment by ellentohn** [comment]
works on iphone 6 and samsung -- Ellen
