### ISSUE TITLE
React Error: "Too Much Recursion" on Various Pages

### ISSUE THREAD

**Issue by archx3** [massenergize/frontend-portal#1313]
### **Description:**

A React error "Too Much Recursion" is appearing in the console on various pages, including the home page. This suggests an issue with the implementation of a `useEffect` hook. The bug is likely causing infinite loops and preventing components from rendering correctly.

### **Severity:** High

This error prevents proper page functionality and hinders user experience.

### **Steps to Reproduce:**

1. Access any page where the error occurs (e.g., Home page).
2. Use the browser's developer console to identify the specific page and component where the error appears.
3. Look for errors related to `useEffect` hooks.

**Expected Result:**

The page loads and functions normally without any console errors.

**Actual Result:**

The page may not render correctly, and the console displays a "Too Much Recursion" error.

### **Additional Information:**

- Provide specific pages where the error is observed (if known).
- Include any relevant code snippets related to the `useEffect` hook implementation (if possible).

**Resolving this bug requires reviewing the `useEffect` implementations on affected pages. Ensure the hook has a clear dependency array to prevent unintended re-renders and infinite loops.**

**Comment by frimpongopoku** [comment]
@archx3  please provide a picture of this error. I cant replicate it.

**Comment by archx3** [comment]
> @archx3 please provide a picture of this error. I cant replicate it.

Sure, see below:
![Uploading Screenshot 2024-05-06 at 4.27.09 PM.png…]()

**Comment by frimpongopoku** [comment]
Your picture is broken. And also, please share the steps that got you there. Tahiru and I have just tried and we all dont see the error.

**Comment by vschiniah** [comment]
@archx3 @frimpongopoku please check this ticket and see if it is still needed?
