### ISSUE TITLE
Change color for the success text for subscription to a community's newsletter

### ISSUE THREAD

**Issue by boatengjephthah27** [massenergize/frontend-portal#1328]
### **Description:**

When a user subscribes to a newsletter, the success notification is a black text that is almost the same as the footer background, making it hard to see

### **Steps to Reproduce:**

1. Visit a massEnergize community portal
2. Scroll to the bottom and subscribe to the newsletter

**Expected Result:**
success text should be legible enough 

**Actual Result:**
a black text that is difficult to see and read

**Comment by BradHN1** [comment]
Similarly - fix the color of the text "Your name and email are confidential..." which shows  below the Subscribe to newsletter.
No black text on a black background....
