### ISSUE TITLE
Creating a new event shows on the campaign's view as unapproved and only disappears after a reload

### ISSUE THREAD

**Issue by boatengjephthah27** [massenergize/frontend-portal#1346]
### **DESCRIPTION**
Created/suggested events upon creation shows at the campaigns tab with the pending approval tag, but disappears after a refresh denying the user access to edit the created event

### **USER STORY**
N/A

**Possible Scenarios**
N/A

**Acceptance Criteria**
- [ ] Suggested events should still show for creators to have a chance to edit till it is approved
- [ ] Suggested events should not show at the campaigns tab but at the upcoming events tab
- [ ] There should be an edit button to edit suggested event

**Additional information**

https://github.com/massenergize/frontend-portal/assets/104381959/99b46d19-6a25-4ed7-8703-d9794d5206bc

**Comment by boatengjephthah27** [comment]
@BradHN1  Do you think this is the right implementation for this?

**Comment by abdullai-t** [comment]
This actually isn't a bug. Newly created events on the user portal will appear in the campaign tab if the time difference between the start date and time is more than a week. For the case of newly created events not showing after a reload, this occurs if the logged-in user credentials are associated with either a community admin or super admin account.
