### ISSUE TITLE
Create deployment alerts in the slack channel

### ISSUE THREAD

**Issue by vschiniah** [massenergize/frontend-portal#1365]
Create alerts for deployments into the slack channel (#deployment-alerts)

Requested by: Brad

**Comment by vschiniah** [comment]
@Opoku-Agyemang has this been completed?

**Comment by abdullai-t** [comment]
@vschiniah, the deployment alert has been successfully configured using AWS Chatbot with Slack integration. Below is how it appears in Slack.
![Image](https://github.com/user-attachments/assets/876b9908-afd0-42b7-ab6b-296b4f291898)
