### ISSUE TITLE
Add To Do button doesn't work anymore

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#145]
This happened after you fixed # 97
My To do list is empty. Yet ever "Add to Do" button I click on the all actions page gives me a pop up that says I have already done it. So something broke here.

![image](https://user-images.githubusercontent.com/30277868/77128280-e2d27900-6a25-11ea-8b63-0ff932476ab5.png)
![image](https://user-images.githubusercontent.com/30277868/77128337-1dd4ac80-6a26-11ea-8e14-4cd574fd20cd.png)

**Comment by kaatvds** [comment]
this now works but same problem with Done button needing same fix. Will make this into a new issue = #148.

**Comment by kaatvds** [comment]
The done it and to do buttons are now truly broken: 
step one: initial indiv action page
![image](https://user-images.githubusercontent.com/30277868/77947186-84ad5d80-7291-11ea-9748-aad159507d30.png)
step two:  I click on Add to Do and button changes to different colors but nothing gets added to To Do List
![image](https://user-images.githubusercontent.com/30277868/77947257-a9093a00-7291-11ea-9a79-73c891815d38.png)

THEN when I click on Done it button, it takes away that action from my done it list AND adds the previous TO DO action to TO DO list
![image](https://user-images.githubusercontent.com/30277868/77947529-0e5d2b00-7292-11ea-8fd0-f0d4bfa1655d.png)

**Comment by kaatvds** [comment]
This now seems to work... Don't know why. Closing.

**Comment by kaatvds** [comment]
On phone, on Indiv action page, when clicking done it, there is no "thank you for adding" popup like on the laptop.

**Comment by ellentohn** [comment]
mixed: worked on laptop for just a testsite for several actions  but NOT for "Action you want to show first" and Christmas Energy" for both of these when I clicked add to do; nothing happened. Worked for other issues.  Same result on iphone did not work for the first 2 actions shown but worked for others.

**Comment by kaatvds** [comment]
created new issue #154  for my comment.
don't know about Ellen's, it works for me for those two actions...
