### ISSUE TITLE
clicking "Add To DO" on indiv action page > blank screen and then backtracking = more blank screens

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#149]
clicking "Add To DO" on indiv action page
![image](https://user-images.githubusercontent.com/30277868/77768371-c7183580-7018-11ea-85e0-92faa71662a0.png)
> blank screen with  url https://community-dev.massenergize.org/wayland/actions/360:
![image](https://user-images.githubusercontent.com/30277868/77768470-e747f480-7018-11ea-8629-3dcbf3f0b58a.png)
back button then takes you to url https://community-dev.massenergize.org/wayland/actions (and still blank)
back button again takes you to url https://community-dev.massenergize.org/wayland ad sill blank...
when back button one more time > url https://community-dev.massenergize.org/ and finally not a blak screen

**Comment by ellentohn** [comment]
Its weird it worked on some of the actions but not others. sometimes I got an orange button once I clicked on it  for the first 2 times I did Add to do" but then on the third action I tried to Add to Do -- I goto a blank screen. I tried it on my iphone

**Comment by ellentohn** [comment]
When I try it on my macbook lap top  it works. BUT it still has the Submit button button which I don't see on the phone -- it appears once I select either done it, to do or more info

**Comment by kaatvds** [comment]
several different things are up now:
1. done it button switches position when clicked = new issue #153 
2. When I click on Add to Do button nothing happens = old issue #145 (reopening)

**Comment by ellentohn** [comment]
Works for everything except  the first 2 actions on Just a Test Site -- where it is not accepted on the individual action-- selecting Add to Do -- it does not turn orange or register on my phone -- I wonder if its a problem with those 2 actions
