### ISSUE TITLE
filter box in all events + also Testimonials

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#150]
same issue as with filter box in testimonials:  #71. Please make same as filter box in All Actions (same font, font size, font color, line spacing, line dividers, etc.

**Comment by OrlyStrobel** [comment]
The spacing is different for "Actions" than it is for "Testimonials" and "Events," and I the font size seems to be different for "Events." See how the "Activism & Community" tab looks for font size reference.  
![Screen Shot 2020-06-17 at 10 18 51 AM](https://user-images.githubusercontent.com/65621001/84909887-39327080-b084-11ea-9985-96679002cd8d.png)
![Screen Shot 2020-06-17 at 10 17 35 AM](https://user-images.githubusercontent.com/65621001/84909891-3afc3400-b084-11ea-8c37-bc1c91a84bcd.png)
![Screen Shot 2020-06-17 at 10 17 24 AM](https://user-images.githubusercontent.com/65621001/84909898-3c2d6100-b084-11ea-9136-87395d8853ad.png)

**Comment by kaatvds** [comment]
yup, still different. The tighter spacing of testimonials is preferable. Maybe make font size smaller to make whole tag (Activism & Community") fit?

**Comment by BradHN1** [comment]
Deployed to Dev
Testing: @OrlyStrobel @kaatvds @ellentohn

**Comment by OrlyStrobel** [comment]
The font size seems right, but the spacing is still different for "Actions" (tighter spacing) than it is for "Testimonials" or "Events." Not hugely noticeable, however: 

![Screen Shot 2020-06-24 at 12 59 05 PM](https://user-images.githubusercontent.com/65621001/85599861-ed02a580-b61a-11ea-8649-8e1f5a17151b.png)
![Screen Shot 2020-06-24 at 12 59 16 PM](https://user-images.githubusercontent.com/65621001/85599872-eecc6900-b61a-11ea-8506-a87c4534bb92.png)
![Screen Shot 2020-06-24 at 12 59 27 PM](https://user-images.githubusercontent.com/65621001/85599880-f0962c80-b61a-11ea-8e0e-b0894601858f.png)
