### ISSUE TITLE
on indiv action page,  done it button switches position when  clicked/unclicked 

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#153]
on indiv action page,  done it button switches position when  clicked/unclicked 👍 

![Screenshot (414)](https://user-images.githubusercontent.com/30277868/77946854-fdf88080-7290-11ea-8588-829b12f57482.png)

![Screenshot (413)](https://user-images.githubusercontent.com/30277868/77946865-02249e00-7291-11ea-919e-053c616148a3.png)

**Comment by ellentohn** [comment]
This is not working for me on the iphone.  see attached. picture of how it looked after I clicked "more info" when I click Add to Do or done it those work. 

ALSO - for the food scraps action item when I click More info nothing happens. 
![Screenshot Issue #153 button position after clicking 3 31 20](https://user-images.githubusercontent.com/60329553/78057936-8c363a80-7355-11ea-8614-fda7d9c43994.png)

**Comment by ellentohn** [comment]
It works fine on my mac book laptop its a phone issue

**Comment by kaatvds** [comment]
on my motorola this still happens: 
![Screenshot_20200409-155026](https://user-images.githubusercontent.com/30277868/78935027-f8ade980-7a79-11ea-92ed-48e7b4539c45.png)

**Comment by BradHN1** [comment]
Testing on laptop - To Do and Done It button positions on my laptop are haphazard, not well aligned and they do move slightly when clicked.  On my iphone5 the buttons don't move but they are positioned too close to one another.  Should be spaced apart to make better use of the screen.  (Also Submit, Cancel buttons are too small and close together.  On the simulated Iphone6 (laptop browser) buttons are better spaced but don't move.

**Comment by kaatvds** [comment]
on PROD, on indiv action page, on laptop, when pressing button it moves around. On Orly's laptop this resulted in the button overlapping. 
![Screen Shot 2020-06-18 at 1 21 14 PM](https://user-images.githubusercontent.com/30277868/85053608-c7802280-b168-11ea-9af2-a34ccd9f6f4f.png)

**Comment by BradHN1** [comment]
Deployed to Dev
Testing: @OrlyStrobel @kaatvds @ellentohn
