### ISSUE TITLE
Date formatting on event listings

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#167]
Events and campaign dates should have the essential and correct information.

By default, events which span multiple dates should not display the times (** unless time specified as applying to all dates ** which would require an API change ** we’ll get there **:
April 15-20, 2020 from 9:30am-3:00pm)

Multi-day events where both dates are within the same year should only show the year after the second date:   March 31 - April 15, 2020
Multi-day events where both dates are within the same month should only show the month once:
April 15-20, 2020

Single date events with a time interval specified should list the date once:
April 20, 2020 from 9:30am-3:00pm

Suggest that for single date event, day of week should be shown, abreviated to 3 letters: Wed Oct 15, 2020 - 9am-5pm)

Font size for the date and time should be 20% larger, just a bit smaller than the title (which should be somewhat larger too.

On individual event page, the word “TO” looks dumb.  Should be lower case in same font as the date/time.
As above, if single date with time interval, no “TO”

[considering also whether times starting on the hour should show 3:00pm or 3pm]

**Comment by BradHN1** [comment]
Still is a case in the one event page where the time is displayed where it isn't in the all events page:
![Screen Shot 2020-05-20 at 7 51 59 PM](https://user-images.githubusercontent.com/12800484/82508645-b2659480-9ad3-11ea-86f4-00b0bf4a7e91.png)

**Comment by jkatofsky** [comment]
My mistake, I thought that was the desired outcome. Should the times never be displayed when the event spans multiple days? @BradHN1

**Comment by BradHN1** [comment]
That same event shows on the all events page as April 6th - November 28th, 2020
Should be consistent.

**Comment by kaatvds** [comment]
is this solved? If not, should this ticket not be open?

**Comment by jkatofsky** [comment]
> is this solved? If not, should this ticket not be open?
> 
> 

I have made the fix - everything is now consistent. The new date format shows up across all pages now.
