### ISSUE TITLE
Action Dates Entry

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#169]
Dependency to API issue #106: Actions taken should have dates associated with them

When an action is taken, give the user the opportunity to enter when the action was taken.  This would be along with asking which real estate unit the action applies to

It would be just the month and year.  The year would be a pull-down with 5 options:
2016 or before
2017
2018
2019
2020
with the default showing for the current year.

The month pull down would default to no month entered (not required to set the month).  Or we could decide to have the month default to the current month.

If the user chooses to skip, it will be entered as "This year, this month".  Which may not be accurate but it is no less accurate than having no idea of the date.

**Comment by BradHN1** [comment]
@dim505 - we reviewed the dialog which asks the date of an action, and decided it couldnt' be deployed as is, but needs to be simplified. 
@kaatvds - can you comment on this proposal?

I suggest the following four options, on a pull-down menu:

**When did you complete the action?**      [note this question needs to something the user will notice]

1. Just completed it!  --> date = now
2. Earlier this year (2021) --> date = three months ago, or Jan 1 of this year, whichever is later
3. Last year (2020) --> date = one year before the current date
4. Before last year --> date = two years before the current date

Also, I would like to add a pull down to set a date for "To Do" actions, with the following choices:

**When are you planning complete the action?**
1.  Very soon  -->  date = now
2. Later this year (2021) -->  date = now + 3 months, or Dec 31 of this year, whichever is earlier
3. Next few years --> date = now + 1 year
4. Not planning but interested --> date = now + 10 years

**Comment by dim505** [comment]
old ticket?
