### ISSUE TITLE
Sign in button showing while I am signed in.  

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#173]
As the picture shows, even though I was signed in as a standard user, the Sign-in button shows and doesn't allow me to sign out.

![Screen Shot 2020-04-13 at 9 34 04 AM](https://user-images.githubusercontent.com/12800484/79124299-027d6880-7d6a-11ea-8125-9037b0b6a991.png)

**Comment by BradHN1** [comment]
This doesn't always happen, but it can happen at least in sandbox on the Cooler Concord site.  The logic for when that button shows the profile name and allows signing out should be improved.

**Comment by BradHN1** [comment]
@Pongo1 - is this the bug which you fixed in the commit "stumbled on login bug -- but fixed."

Another question: there are references to both _window.localStorage_ and just _localStorage_ which seem to be used interchangeably.  Are they the same?

**Comment by BradHN1** [comment]
@OrlyStrobel @kaatvds @ellentohn - I think this may be fixed.  Make sure the log in button changes properly whenever you sign in.

**Comment by OrlyStrobel** [comment]
@BradHN1 works on my computer and my iphone. Closed it and moved it to validated in QA
