### ISSUE TITLE
Don't show past events in "Upcoming Events"

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#174]
If no upcoming events, the home page should say "no upcoming events".

![Screen Shot 2020-04-13 at 10 27 53 AM](https://user-images.githubusercontent.com/12800484/79128507-a1599300-7d71-11ea-9140-593075306bd7.png)

**Comment by BradHN1** [comment]
@OrlyStrobel - check whether past events show up under "Upcoming Events".

**Comment by OrlyStrobel** [comment]
@BradHN1 yes, past events are showing up
