### ISSUE TITLE
Teams: team box text is overlapped with the X on the pop up box.

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#180]
When we add text to describe the team the text is overlapped with the X on the pop up box.

**Comment by kaatvds** [comment]
<img width="759" alt="Screenshot 2020-04-20 10 08 36" src="https://user-images.githubusercontent.com/30277868/79760941-ca889f00-82ee-11ea-84ab-98b568eef125.png">

**Comment by BradHN1** [comment]
This pop-up box should go away in favor of the single Team page.

**Comment by BradHN1** [comment]
I still see overlap with text and the X if the text is long enough to get across the modal box.

**Comment by BradHN1** [comment]
Superceded by individual teams page
