### ISSUE TITLE
Teams logo don't display

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#184]
Team Logos -- the admin interface has a place to upload a team logo, but they are not currently displayed on the community portal -- lets display the logo in first column

**Comment by BradHN1** [comment]
Logo is a bit too small to see detail.  Increase dimensions by 50%
Vertical alignment is good, but vertical alignment in the other columns should be the same.

**Comment by Pongo1** [comment]
![Screenshot 2020-05-20 at 11 26 41 AM](https://user-images.githubusercontent.com/26961591/82441065-e2d61000-9a8c-11ea-998b-2d0c51203ed0.png)
like this big?

**Comment by Pongo1** [comment]
![Screenshot 2020-05-20 at 11 28 09 AM](https://user-images.githubusercontent.com/26961591/82441151-08fbb000-9a8d-11ea-8372-ee842db46d2d.png)
 Used to be like this

**Comment by BradHN1** [comment]
That is better, let’s make it a bit bigger still, so 2x the original size.  I’ll confirm with the others and check on mobile.


++++++++++++++++++++
Bradley Hubbard-Nelson
221 Nashawtuc Rd
Concord, MA 01742
bradhn@mindspring.com
hubbardnelson.org <http://hubbardnelson.org/>
Tel: 978-505-7128 (cell)
