### ISSUE TITLE
Teams: add individual team page

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#185]
Be able to create url to take users directly to a specific team page e.g., https://community.massenergize.org/JCAN/teams/CongregationBethEl

**Comment by jkatofsky** [comment]
Design of page outlined on [this google doc](https://docs.google.com/document/d/1-Uk7NM1VVzAeCT5wDAWdFsPnULywNOaGB45eYzjLVBw/edit)

**Comment by kaatvds** [comment]
On laptop actions data looks good. On phone under Actions Completed it says "the actions data for this times could not be loaded" > is that because it is not possible to display the kind of graph? That would make sense but then the message should read: "The actions data is available on a larger screen".
The way it shows is like there is a bug.
