### ISSUE TITLE
impact page on laptop: donuts  cut off

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#187]
One of our cadmins had this happen, on her laptop.
On my laptop it's okay....
![sunwoo_screenshot](https://user-images.githubusercontent.com/30277868/79704971-e30ea000-8281-11ea-8d3f-5a2c8a18ee21.jpg)

**Comment by BradHN1** [comment]
Donuts still get clipped for certain screen sizes. Pongo-new-development d9f7a324c0c28d61c6659fc5e4fff40c82ae8d2d

<img width="1028" alt="Screen Shot 2020-05-18 at 3 51 27 PM" src="https://user-images.githubusercontent.com/12800484/82253874-d1bbc080-991f-11ea-80cc-11bc07d7bf02.png">

**Comment by Pongo1** [comment]
Yes, the fix was part of the batch you reverted. So dont worry, it will come again. loool. :)
