### ISSUE TITLE
when user has more than one household and selecting action: allow both households selected

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#191]
when user has more than one household and selects an action they are asked for which household. They should be able to select both households. Right now when they click Done in order to add it to the other household too,  it just takes the action away from the first household.

**Comment by BradHN1** [comment]
Deploying to dev site, please test laptop and mobile, make comments and re-open if there are problems: @OrlyStrobel  @ellentohn

**Comment by OrlyStrobel** [comment]
@BradHN1 works on both my laptop and my mobile. Should I move this to "Validated in QA?"
