### ISSUE TITLE
Add an image to the teams board page

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#192]
Add something visual to make it pop. Frimpong as quick fix I can send you a picture that you can hard code in. We can make Cadmin upload of picture for later.

**Comment by ellentohn** [comment]
Kaat will mock this up to have a photo and also provide space where Samdin and Cadmins can enter some text, we can have basic text that they can edit?

**Comment by kaatvds** [comment]
Okay I think we have consensus on the interim quick fix for the teams page.
![TEAMSpage2](https://user-images.githubusercontent.com/30277868/82739748-399f4c00-9d10-11ea-865f-d2a29485bc68.jpg)

**Comment by kaatvds** [comment]
@Pongo1 Frimpong I will slack you a jpg of the image up top.
