### ISSUE TITLE
Teams board: reorder by clicking on column headings

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#194]
The teams list comes out sorted by Actions/household, which is fine.  

Make column headings clickable to be able to sort on Name alphabetically (ascending order), Households, Actions or Carbon impact (default to descending order) to sort by those fields as well.  As usual clicking a second time on the heading would reverse the sort.  So need a ^ or v next to the column header when it is the sort key to indicate the sort direction.

**Comment by BradHN1** [comment]
Deployed to Dev community portal - please test on laptop and mobile, that sorting works on every column, make comments and re-open if there are issues.  @OrlyStrobel

**Comment by OrlyStrobel** [comment]
@BradHN1 works on both my laptop and my mobile. Again, let me know if I should move it to "validated in QA..."

**Comment by BradHN1** [comment]
Great - you can move it forward...

++++++++++++++++++++
Bradley Hubbard-Nelson
221 Nashawtuc Rd
Concord, MA 01742
bradhn@mindspring.com
hubbardnelson.org <http://hubbardnelson.org/>
Tel: 978-505-7128 (cell)
