### ISSUE TITLE
Edit old testimonials to change name of submitted

### ISSUE THREAD

**Issue by ellentohn** [massenergize/frontend-portal#207]
Allow Cadmin to edit old testimonials to put in a name of the person who submitted.

**Comment by OrlyStrobel** [comment]
@BradHN1 I am not sure I know how to edit anything on prod. Do I have this capability @ellentohn  @kaatvds?

**Comment by kaatvds** [comment]
Hi @OrlyStrobel, yes, prod is the usual place (http://admin.massenergize.org/) - where you were helping Ellen with JCAN etc, before we confused you with this dev business :)

**Comment by kaatvds** [comment]
@Brad, you meant dev?

**Comment by BradHN1** [comment]
Once Sam deploys latest API (hopefully today) with the community and admin sites now updated, we still need to edit the testimonials in prod, make sure names look reasonable.
