### ISSUE TITLE
Testimonials remove anonymous option

### ISSUE THREAD

**Issue by ellentohn** [massenergize/frontend-portal#208]
we want folks to leave some name.

**Comment by OrlyStrobel** [comment]
I could still write my preferred name as anonymous and it shows up as such on the site: 
![Screen Shot 2020-08-07 at 11 05 37 AM](https://user-images.githubusercontent.com/65621001/89659457-ee6ff080-d89d-11ea-9d13-7b85908678f5.png)

**Comment by BradHN1** [comment]
Yes, but we don't encourage you to do that by giving you the choice, and a community admin should reject that testimonial.
