### ISSUE TITLE
CAdmin team approval process

### ISSUE THREAD

**Issue by ellentohn** [massenergize/frontend-portal#209]
Allow Cadmins to enter text under the word Team -- to say more about this for their community, can we also have default text that we put and they can edit

**Comment by BradHN1** [comment]
@jkatofsky  @kaatvds - I'm not sure this is right yet so didn't close the issue.  There should be both a tagline and a description on the individual team page; just the tagline on the teams page.  But the database may have had the same text in both.

**Comment by kaatvds** [comment]
how would I as a super admin know this team is awaiting permission? I got no email or slack message, and there is no column in the All Teams list to indicate something hasn't been approved...

**Comment by kaatvds** [comment]
this may be re. #356: old teams have no admins.

**Comment by kaatvds** [comment]
This ticket is confusing as the title doesn't reflect the content of the issue.... Which is addressed in #244. So should we close and take this off the board?
