### ISSUE TITLE
rewrite two emails sent to people creating profiles

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#213]
The confirmation should read

Kaattesting, Welcome to Energize Wayland
--
We are thrilled to have you join our local efforts to address the climate emergency and build local resilience.

Get started with Energize Wayland

Take Action
See your options for meaningful action to reduce our greenhouse gas emissions. Find actions you want to take and add them to your to do list. Also, let us know what you have already done, so we can count your efforts toward our community goal. 

Join the Collective Genius!
Want to be more involved in the community? Come to our events, join or create a local team, write testimonials, and see how we can make a difference together. 

Find Service Providers.
Need help completing an action? We recommend local service providers and your neighbors are sharing testimonials about what they've done and who they hired. 

EXPLORE NOW

**Comment by Pongo1** [comment]
HI @kaatvds , this particular part of sending message, is not done on the front end. Maybe it should be on the backend board ??

**Comment by kaatvds** [comment]
text okayed by all

**Comment by BradHN1** [comment]
Please test this @kaatvds @OrlyStrobel
