### ISSUE TITLE
Menu: remove all communities and rearrange top menu bar

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#214]
99% of our use cases won't look at other communities. Let's remove it and make home just go home. We can put "All Massenergize Communities" in the footer.

**Comment by BradHN1** [comment]
Good idea.  Suggest "Other MassEnergize Communities" be an option under "About Us" as another option.  I do think more people than 1% will check out their neighboring communities.

**Comment by BradHN1** [comment]
Teams is a heading

Contact us combiend with about us.

remove All Communities from under Home menu Tab

**Comment by jkatofsky** [comment]
Just a note for whenever this ticket get tackled: menu info is fetched from the API, and some ad-hoc modifications are done to it on the front-end in `AppRouter.js`

**Comment by kaatvds** [comment]
Home in the nav bar is now just home = great
BUT I don't see Brad's other suggestions 
- Teams is a heading
- Contact us combiend with about us.
Maybe needs more explanation?

**Comment by kaatvds** [comment]
Home in the nav bar is now just home = great
BUT I don't see Brad's other suggestions
Teams is a heading
Contact us combined with about us.
Maybe needs more explanation?
