### ISSUE TITLE
Testimonials: User submits photo with testimonial

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#239]
User should be able to upload a photo with a testimonial.
Appropriate warning not to use copyright material.
This is very important, the way every social media site works.

**Comment by OrlyStrobel** [comment]
@BradHN1 there is an option to upload a photo, but I don't see anything warning against copyright

**Comment by BradHN1** [comment]
I added a statement about it being your photo, or making sure it isn’t copyrighted.  Thanks


++++++++++++++++++++
Bradley Hubbard-Nelson
221 Nashawtuc Rd
Concord, MA 01742
bradhn@mindspring.com
hubbardnelson.org <http://hubbardnelson.org/>
Tel: 978-505-7128 (cell)
