### ISSUE TITLE
Properly manage loading & error state across portal

### ISSUE THREAD

**Issue by jkatofsky** [massenergize/frontend-portal#243]
Pages such as the events page and actions page do not display the LoadingCircle component while their data is loading in. This causes them to briefly render messages saying that there are no events/actions in the community before the data gets rendered. The OneActionPage also has an issue with briefly displaying the 404 page before the loading circle shows up.

Need to go across the portal and properly use the LoadingCircle component to provide a visual indication that data is loading, where applicable, and save the "no ___ in this community" or 404 pages for when they are actually necessary.

Furthermore, tweak the LoadingCircle component itself so that it better fits within divs that are not the size of the entire viewport. For example, I needed to use the raw loading GIF instead of the LoadingCircle component to display the loading state of the teams actions graph, lest the LoadingCircle change the parent div size.

Lastly, for all `fetch` functions, setting `loading` to `false` can be done in the `finally` function, to avoid code duplication.

**Comment by jkatofsky** [comment]
For the one actions page and one events page, this should be fixed through my loading state changes [here](https://github.com/massenergize/frontend-portal/commit/5c38d59d18372e09f64031b0d444e22a6ee26f0d). Now, need to make similar fixes for other pages across the portal.

**Comment by jkatofsky** [comment]
Furthermore - we need to wrap loading code in a try-catch block to catch errors. This can help avoid ungrateful crashes on outdated browsers.

Example: `finally()` not supported on old versions of Safari or Internet Explorer. (discovered in #274 )

**Comment by jkatofsky** [comment]
A list of changes I'm making:

1. more graceful error handling in all code - see [here](https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html)
2. proper use of loading circle on all pages
3. instead of rendering Error404 component _within_ a page on error, set up an error route that renders an error page, with optional `errorMessage` props, and redirect to it when errors happen across the portal. this page can contain information about how to report the error to MassEnergize

**Comment by BradHN1** [comment]
Test in dev before prod deployment: @OrlyStrobel @kaatvds @BradHN1 @jkatofsky
