### ISSUE TITLE
Team create/edit form & parent teams

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#244]
The Request Team Creation button should not go to the generic contact admin form.  Instead it should go to a form which explains what team creation involves, that the person requesting the team would be a team admin, and have them view policies and ok them.

A few of the things on the form:

Team admin (the user): e-mail, phone, display name
Whether e-mail and phone should be viewable by team members
Closed vs open team
Team name
Team tagline
Team description
Team goals (households, actions, carbon reduction)
Team banner upload
Team video
Upload list of team member e-mails

When the user submits, that request will be sent to the community admin before the team goes live.

**Comment by jkatofsky** [comment]
Changed the title of this ticket to encapsulate all the front-end changes corresponding to the teams API model additions.

**Comment by jkatofsky** [comment]
Adding ticket to the admin portal, as its forms will need to be updated with these changes as well.

**Comment by kaatvds** [comment]
@jkatofsky this ticket is still open, does this mean it failed a test (and I don't need to test it :). Or did you forget to close it, in which case I do have to test it.

**Comment by jkatofsky** [comment]
@kaatvds i only left it open because it hadn't been tested with all of the other site changes at the time i stopped working for ME. If it's been tested and works, can go ahead and close.

**Comment by kaatvds** [comment]
small problem: spelling mistake "recieve"
![image](https://user-images.githubusercontent.com/30277868/94588344-c5daf600-0251-11eb-95f6-c80c7aab8d2a.png)

**Comment by kaatvds** [comment]
also (bigger issue) how would I as a super admin know this team is awaiting permission? I got no email or slack message, and there is no column in the All Teams list to indicate something hasn't been approved...

**Comment by kaatvds** [comment]
this time I created a team without a parent. 
This time it didn't tell me that an admin had to approve it. (I was signed in under a profile this is not an admin, but just a user).
![image](https://user-images.githubusercontent.com/30277868/94590330-83ff7f00-0254-11eb-809f-447121eab20e.png)

**Comment by kaatvds** [comment]
Okay, as a Cadmin for Wayland I got a team approval  email. but when I clicked on the link it gave me a blank/purple screen: 
![image](https://user-images.githubusercontent.com/30277868/94592596-0d17b580-0257-11eb-8c17-fcdcaa0b7044.png). Maybe a glitch.
I separately logged in as Sadmin and checked the teams list. CLicked ont hat team: another blank list and refreshing brought me to the blank/purple screen again...
![image](https://user-images.githubusercontent.com/30277868/94594046-6c75c580-0257-11eb-96b6-45c3ebc0277d.png)

**Comment by kaatvds** [comment]
team creation email to user who created it leads to dev site. and on the canary when refreshing the page to see that team after cadmin approved  it  creates infinite loop

![image](https://user-images.githubusercontent.com/30277868/98009481-94f75f00-1dc3-11eb-9d4c-0929e0397e05.png)
