### ISSUE TITLE
css not responsive to browser viewport

### ISSUE THREAD

**Issue by satra** [massenergize/frontend-portal#25]
on https://community.massenergize.org/wayland/ - the CSS is not responsive to the browser viewport. in my current default viewport the following is observed.

see sign in button
![image](https://user-images.githubusercontent.com/184063/72812430-7c042f80-3c2f-11ea-85a7-e23e9b16d3bf.png)

see the top of the impact circles
![image](https://user-images.githubusercontent.com/184063/72812446-845c6a80-3c2f-11ea-8134-cf7b07fcf414.png)

see the bottom of the event panels
![image](https://user-images.githubusercontent.com/184063/72812500-9b9b5800-3c2f-11ea-8885-a4c0b8aebbcf.png)

**Comment by kaatvds** [comment]
Reopening. not sure why this was closed. Issue persists. Cf. creenshot
![image](https://user-images.githubusercontent.com/30277868/74939677-4e411080-53be-11ea-8e20-4ee6a280cf78.png)
