### ISSUE TITLE
cards of testimonials not  lining up

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#256]
the cards overlap.
![image](https://user-images.githubusercontent.com/30277868/84452198-2dc5ec00-ac23-11ea-8fda-4c5041e0de7a.png)

**Comment by OrlyStrobel** [comment]
This still seems to be an issue both in prod and in dev (I tested in dev again to see if it just hadn't been pushed yet, but it seems like an issue there too)

**Comment by BradHN1** [comment]
I don't know the status of this; @OrlyStrobel  can you check this in dev?
