### ISSUE TITLE
acknowledgement to user that message has been sent

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#26]
I filled in the Contact Admins Here form, clicked Send Message. The form clears, but I'm not certain an email was sent. Can we have a better acknowledgement to the user. For instance, the form should disappear after the user clicks Send Message and the following message should be displayed: "Thanks for contacting the community administrator. You should receive a response within a few days."

![image](https://user-images.githubusercontent.com/30277868/73185323-d992f300-40eb-11ea-9166-ecc08ebc61f6.png)

**Comment by BradHN1** [comment]
I added an alert so the user gets a message.  It could be done better.

**Comment by BradHN1** [comment]
Tested in Dev.  Not yet deployed to Prod
