### ISSUE TITLE
After login redirect, return to original page as opposed to profile page

### ISSUE THREAD

**Issue by jkatofsky** [massenergize/frontend-portal#264]
For example, when signed out and viewing an action, clicking "Sign In" below the action takes you to the sign-in page, and after signing in, you are redirected to your profile, instead of back to the action that you originated from. This is un-intuitive because the user signed in for the purpose of interacting with that action.

Parameterize where to redirect after a user signs in.

**Comment by BradHN1** [comment]
Testing by @OrlyStrobel

**Comment by OrlyStrobel** [comment]
Looks good in prod on mobile and laptop @jkatofsky @BradHN1
