### ISSUE TITLE
White screens in Safari

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#274]
Someone from Framingham reported: "was just on the Mass energize page tapping on actions to compare with the actions I’m working on and each time I click on them the screen becomes fully white! I’m not sure if that is due to my device or the site itself, but I thought I’d say something just in case - I can only successfully view the actions with my Chrome browser instead of Safari"

I tested on Chrome and there does seem to be a split-second white screen after I click (more info on the All actions page > Indiv action page). Maybe I just never noticed it. 

Maya tested on Safari and she too gets the white screen.

**Comment by jkatofsky** [comment]
this issue belongs with #243 - closing and adding issue description there
