### ISSUE TITLE
when creating new account: no link to continue

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#28]
I fill in register (email, password twice), submit. I get email. When I click on the link in that email I just get "Your email has been verified, You can now sign in with your new account". Would be good to have a link to the site right there as well. This way user needs to ope a new tab, type in the url...

![image](https://user-images.githubusercontent.com/30277868/73195111-495caa00-40fb-11ea-925c-25115ab54b38.png)

**Comment by BradHN1** [comment]
Attempting fix in BHN-bugfixing branch; will require testing in Dev.

**Comment by BradHN1** [comment]
Tested in Dev, not yet in Prod
