### ISSUE TITLE
Resize smaller & center buttons on home page

### ISSUE THREAD

**Issue by ellentohn** [massenergize/frontend-portal#281]
Resize buttons: "Our Impact" & "See All Events" -- these should be smaller and still be center. We discussed with on the Friday  am call.

**Comment by BradHN1** [comment]
@ellentohn @OrlyStrobel - check out these buttons on mobile and laptop, do they look ok?

**Comment by OrlyStrobel** [comment]
@BradHN1 "our impact" looks good on both phone and computer- "see all events" looks the same in dev and prod as near as I can tell, but it doesn't look unusually big to me. I'll wait to see what @ellentohn thinks before moving it
