### ISSUE TITLE
Social media share buttons on individual pages

### ISSUE THREAD

**Issue by jkatofsky** [massenergize/frontend-portal#283]
On the pages for individual actions, events, teams, etc, want to include metadata (for link previews) using react-helmet, and then use Facebook's & Twitter's (and any other applicable sites') share button code to allow users to share these pages.

https://developers.facebook.com/docs/plugins/share-button/
https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview
https://github.com/nfl/react-helmet

**Comment by jkatofsky** [comment]
Suggestions welcome about which pages should have these buttons and which sites we should include buttons to @BradHN1 @apowelka @kaatvds

**Comment by jkatofsky** [comment]
Using react-share instead, to avoid loading SDK scripts and easily maintain a consistent look.

**Comment by BradHN1** [comment]
@OrlyStrobel @kaatvds - try the social media shares.  The redirect to the site is not what we want, but Facebook technical issues make it difficult to do it right.

**Comment by BradHN1** [comment]
This is what the facebook share does:
![Screen Shot 2020-07-20 at 9 16 01 PM](https://user-images.githubusercontent.com/12800484/88001866-20780900-cacf-11ea-9c57-e08cc7d9de47.png)

The LinkedIn share gets an error:
![Screen Shot 2020-07-20 at 9 17 01 PM](https://user-images.githubusercontent.com/12800484/88001871-21109f80-cacf-11ea-8f94-aa05b021f21c.png)

**Comment by jkatofsky** [comment]
Will look into the LinkedIn error; tons of people online are having issues with their share feature. If I can't be sure it will work, will deprecate that button before prod deploy. 

The new meta tags don't seem to be making a difference with the link preview yet. Could be that I made some small mistakes with them, or that a web crawler hasn't got our updated site info or both. Will investigate.

Lookout for another PR today

**Comment by kaatvds** [comment]
This works BUT
the buttons are so far down (because of my long DONE IT list)
![image](https://user-images.githubusercontent.com/30277868/97902851-299e8600-1d0c-11eb-83c9-e613ff9d2aab.png)
WOuld be nicce to put themm right underneath the text

**Comment by jkatofsky** [comment]
@frimpongopoku could you do a quick fix for this where you change the parent element of the social media buttons on the single action page?
