### ISSUE TITLE
Teams: team members not showing on Teams leaderboard

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#29]
I signed up as a member of the Wayland Solarizers Team, and on the Team leaderboard have an option to quit that team.... but my numbers are not showing. It read zero across the board.

![image](https://user-images.githubusercontent.com/30277868/73195676-46ae8480-40fc-11ea-9333-83a5c7f821ba.png)

**Comment by BradHN1** [comment]
Fixed in BHN-bugfix branch.

**Comment by BradHN1** [comment]
Tested in Dev, not yet in Prod

**Comment by kaatvds** [comment]
tested on En Wayland: I am a member of the SOlarizers Team but doesn't show up in leaderboard : all still 0

**Comment by ellentohn** [comment]
just tested in Dev and I signed up for Solarizers. and I can see my actions and household so it seems to be working for me in Dev

**Comment by kaatvds** [comment]
closed because duplicate of #29
