### ISSUE TITLE
Delete household problem

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#295]
I added two households on Dev, and tried to delete the third one.  Nothing happened. In Javascript console get the following error:
users.households.remove Error: RealEstateUnit matching query does not exist.

Here is the screen:
![Screen Shot 2020-08-11 at 12 20 15 AM](https://user-images.githubusercontent.com/12800484/89856881-80ab1980-db68-11ea-99d1-e3a59770171f.png)

**Comment by frimpongopoku** [comment]
Again, this bug cannot be replicated on my end. However, I have gone to the line specified in the console, and placed a check for null params passed in future -- just in case.

I will close this and move to back log then.
