### ISSUE TITLE
url in icon box leading outside our site

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#30]
Newton would like one of the icon boxes to refer the user back to their Green Newton site. I put that url in the url box on that icon box but it just adds the url, so: https://sandbox.community.massenergize.org/greennewtonhttps://www.greennewton.org
Can we fix this?

**Comment by BradHN1** [comment]
Fixed in BHN-bugfixing branch.  External url will open in new tab.

**Comment by BradHN1** [comment]
Validated that it works on the Green Newton site in Prod
