### ISSUE TITLE
Home page: Center justify featured events and campaigns

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#300]
On laptop, if only one featured event it shows up left justified.

**Comment by frimpongopoku** [comment]
@jkatofsky  I don't think I am that nice man....  🤣  🤣  🤣  . 
Anyway, on a more serious note -- yeah, I will quickly finish with "more pressing" tickets and join in on the general cleanup. 
I believe now, we can actually afford this clean up  -- there is more of us! 
It used to be only Sam, Brad, and I, and there was literally always something more important to do somewhere, than cleanup for better developer experience 🤣  🤣 🤣  
🥂 🥂  cheers! 🎊
