### ISSUE TITLE
DEV: Indiv service provider page: blank and stuck

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#311]
clicking on an indiv provider lands you on a blank page fr which you can't even go back" to previous page

![image](https://user-images.githubusercontent.com/30277868/92160220-ab516080-edfc-11ea-9257-20c589d98c99.png)

**Comment by frimpongopoku** [comment]
This ticket is also already fixed @kaatvds  && and @BradHN1 please take a look again. Here is a link https://community-dev.massenergize.org/wayland/services/58
