### ISSUE TITLE
DEV: Impact page: X axis elements not abbreviated with "..." so long ones cut off

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#314]
![image](https://user-images.githubusercontent.com/30277868/92161270-629aa700-edfe-11ea-97c2-53fac71b842c.png)

on Prod this looks better:
![image](https://user-images.githubusercontent.com/30277868/92161292-6a5a4b80-edfe-11ea-834e-8cf35dedb1af.png)

**Comment by kaatvds** [comment]
reopened because now not whole title shows up
![image](https://user-images.githubusercontent.com/30277868/97707526-cacbd900-1a8d-11eb-9d47-547a7dc29439.png)

**Comment by kaatvds** [comment]
Also: Abbrev for Land, Water... is Land, (with comma). With hover it should also show the whole title

**Comment by frimpongopoku** [comment]
So, @kaatvds I managed to remove the comma. However, the second part you are looking for, is too much to ask for, from both libraries that we are currently using 🤣 🤣 🤣 . 
Whatever content we pass to the library to display on the x-axis is what we will get on hover. 
We dont control those features. We can only pass the data, specify the type of graph, and play with the colors, thats all -- sadly.

I can do more research on things that allow this feature later though.....

**Comment by kaatvds** [comment]
okay, let's leave this till later. This is not a critical ticket, though...
