### ISSUE TITLE
DEV: can't login through facebook

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#319]
"App Not Setup: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions."

![image](https://user-images.githubusercontent.com/30277868/92163827-4dc01280-ee02-11ea-9ef0-0af533b7f901.png)

**Comment by frimpongopoku** [comment]
Fix is related to this [ticket](https://github.com/massenergize/frontend-portal/issues/354)

**Comment by kaatvds** [comment]
this is addressed in #354, so closing this and removing from board
