### ISSUE TITLE
DEV: Resetting password failed

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#320]
![image](https://user-images.githubusercontent.com/30277868/92164068-bd360200-ee02-11ea-97e9-e6ea336159e2.png)

**Comment by dzheng21** [comment]
@kaatvds Is this still an issue? i have tried replicating it but it hasn't failed for me.

**Comment by kaatvds** [comment]
works now :)

**Comment by kaatvds** [comment]
didn't get an email for a while (couple of minutes). Then when it arrived I clicked the link and it says " Your request to reset your password has expired or the link has already been used"

**Comment by kaatvds** [comment]
I tried again, this time the link worked...

**Comment by frimpongopoku** [comment]
@kaatvds , so should the ticket be closed....??? The link expiring, is normal behaviour. It has to expire if you take tooo long to access it, its for safety reasons.

**Comment by kaatvds** [comment]
I clicked the link as soon as I got the email... But yes, let's close it, because I couldn't replicate it.
