### ISSUE TITLE
DEV: when changing name and nickname on profile: no feedback and doesn't work

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#322]
click submit. nothing seems to happen. Dialog box stays open.  only "cancel" works by closing it: changes not retained
![image](https://user-images.githubusercontent.com/30277868/92165133-8eb92680-ee04-11ea-8bac-7eead868bc0b.png)

**Comment by kaatvds** [comment]
still a problem: can edit the name but when press to submit nothing happens/changes

**Comment by BradHN1** [comment]
API fix

**Comment by kaatvds** [comment]
This works BUT
in edit profile modal delete the "email not editable option" because that IS now an option in under a different tab...
![image](https://user-images.githubusercontent.com/30277868/97898756-4afc7380-1d06-11eb-8384-bd7ea95a174e.png)
