### ISSUE TITLE
DEV: in profile joined JOshTopia: it added a line in the list but both community names disappeared AND couldn't leave it

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#324]
![image](https://user-images.githubusercontent.com/30277868/92165835-a9d86600-ee05-11ea-9605-f75ade8b7584.png)
(also stuck: after that I can't delete a community and refreshing shows error page
![image](https://user-images.githubusercontent.com/30277868/92512962-92babf00-f1dd-11ea-93a3-5894392297ac.png)

**Comment by frimpongopoku** [comment]
The fix is in an [API](https://github.com/massenergize/api/issues/199) change

**Comment by BradHN1** [comment]
I checked it and fixed it not to automatically add the current community to the list.
