### ISSUE TITLE
DeV: edit your profile panel layout is confusing

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#330]
On profile, click triangle next to name: choose edit your profile: the label info on what info is shown should be given first, that is, above the box with the info, not below. The way it looks now, with the  green stripe and then a space and then the label looks like it applies tot he box below, while it applies to the box above. Confusing. 

![image](https://user-images.githubusercontent.com/30277868/92511081-d5c76300-f1da-11ea-8cf2-6dee17052404.png)

**Comment by kaatvds** [comment]
Awesome! BUT.... not the change email and password are missing again?

**Comment by kaatvds** [comment]
= #412

**Comment by BradHN1** [comment]
those dialogs seem to work for me.
