### ISSUE TITLE
DEV: profile: list of communities: clik on eye > error page

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#331]
![image](https://user-images.githubusercontent.com/30277868/92512663-1f18b200-f1dd-11ea-9a6c-422d49267e7b.png)

**Comment by dzheng21** [comment]
this error is interesting, sometimes there are no communities loaded whatsoever (in community-dev, this is the case, but not on my local machine) -- it also seems like the url is correct but for some reason the page decides not to load.

**Comment by dzheng21** [comment]
communities.join permission_denied -> error when adding new community
