### ISSUE TITLE
DEV: doing an action in a community I am not a part of adds that community to my profile

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#333]
Doing an action in a community I am not a part of adds that community to my profile - and also makes all the names in the myy communities list in my profile disappear...

**Comment by apowelka** [comment]
still broke. Chrome. I can complete actions and am logged into all communities

**Comment by kaatvds** [comment]
same as #409?

**Comment by kaatvds** [comment]
doesnt' seem to be the case.
