### ISSUE TITLE
Top bar menu: "Home" only to home page 

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#34]
feedback from communities: the people going to their site will not want to know about "other communities". When clicking on Home in top bar menu, no dropdown, instead straight to home.

**Comment by BradHN1** [comment]
But there should be an easy way to get to the Communities selector.  Perhaps the breadcrumbs could say something like:
Communities -> communityname Home -> etc.

**Comment by kaatvds** [comment]
Newton folks made the point that most people will be on the Newton site because they send them there, and they won't be interested in any other communities. Perhaps we could write a line into the  non-optional MassEnergize part of "About us" like "MassEnergize works with other communities" with a link to https://www.massenergize.org/communities/. Also put a line in the footer? Newton was I think pointing to there being as little as possible confusing the branding of the Newton site as for Newtonians.

**Comment by BradHN1** [comment]
Identical to 214
