### ISSUE TITLE
DEV: FIlters only show the categories, not the other tags (impact, cost)

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#349]
Is that what we want for this version?

**Comment by apowelka** [comment]
No, I would like the cost and impact filters to be usable

**Comment by kaatvds** [comment]
I changed it from question to bug

**Comment by kaatvds** [comment]
the headings for those filters are back = great!
but the way it looks doesn't invite a user to click that green heading box (it doesn't look like a button). 
Also, there is more space underneath the "cost" heading whcih make it looks like there is something missing = confusing.
![image](https://user-images.githubusercontent.com/30277868/94586502-4e0bcc00-024f-11eb-9497-8ddd763f649d.png)

**Comment by BradHN1** [comment]
@frimpongopoku - assigning this to you; see Kaat's comments right above

**Comment by kaatvds** [comment]
reopening: see last comment

**Comment by kaatvds** [comment]
it is still not clear that those filter headings are clickable buttons: ca you

**Comment by kaatvds** [comment]
good enough for now, let's  revisit later.
