### ISSUE TITLE
Home page: shading of text in icon boxes

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#35]
right now greyed out shading for titles and blacker for subtitles. 
Feedback is they greyed out seems like it is an inactive link. Would be solved if reversed: black for title, grey for subtitle
![image](https://user-images.githubusercontent.com/30277868/73204947-f50ef580-410d-11ea-81e2-870dffdc940d.png)

**Comment by BradHN1** [comment]
Have fixed this in BHN-bugfixing branch.  For review.
