### ISSUE TITLE
DEV: orange-green color scheme  

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#350]
It looks awesome for Wayland since orange is our town color but other towns will not like it. You suggested a choice of colors, and Sam a color wheel.... Would be great. Making this a ticket so we don't forget.

**Comment by BradHN1** [comment]
For now, it is decided to use the Green (same as in all buttons) for all bars within Action cards, Event cards, Testimonial cards and vendor cards.  And also the bars at top of submenu when clicking on the top menu bar

**Not a customizable color, that will come later after we deploy to Prod**

**Comment by kaatvds** [comment]
Hi Team, we're getting feedback about redesigning the Action Card so we also solve the photo cropping problem. I am proposing something like this:
![Screenshot (705)](https://user-images.githubusercontent.com/30277868/95480290-be0a0880-0959-11eb-86e6-2e8165c96c61.png)
@frimpongopoku Frimpong, we should talk about this. Will slack you.
