### ISSUE TITLE
Facebook Restriction Appeal

### ISSUE THREAD

**Issue by frimpongopoku** [massenergize/frontend-portal#354]
So facebook disabled our application because we could not provide information about MassEnergize when were asked. 
This is definitely not the end for our facebook authentication, we can appeal this by doing exactly what they asked for -- which is provide information about MassEnergize. I remember @BradHN1  said he'd take charge of this in one of our bi-weekly meetings.... So, I will just assign him, and **comment** out our facebook authentication in the code base, until our ban is lifted.

After this is solved, I will get facebook to work again with the new API. It seemed broken in dev mode anyway. LOL!

![Screenshot 2020-09-29 at 10 22 20 AM](https://user-images.githubusercontent.com/26961591/94546938-17798580-023e-11eb-9c20-831a3a28dad7.png)

At the moment, if you try to sign in  or register with facebook and you arent registered as a ME developer, 
you will get the alert shown below 

![Screenshot 2020-09-29 at 10 36 44 AM](https://user-images.githubusercontent.com/26961591/94548185-dda97e80-023f-11eb-99ae-2a44407290bf.png)

Just as @kaatvds  caught in this [ticket](https://github.com/massenergize/frontend-portal/issues/319)

**Comment by kaatvds** [comment]
Frimpong taking the lead on this
