### ISSUE TITLE
title bars on Event card and other cards

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#366]
On the event card in all events, 

on the colored bar under the pic, put only the event title and make it larger font: same size and placing as the title on the action card.  allowing 40 characters across the card
Same background color as for action cards
then under that, as it is now, the summary of the event
then under that, inside that striped box where the venue is now, put first the date, then the place. No need to say "venue" and "date" :those are self-explanatory.

In the time PM should be all caps (not "Pm") - same for AM

**Comment by BradHN1** [comment]
See that all the points in the first comment are completed as specified

**Comment by apowelka** [comment]
Banner and font for Actions and Events do not match.
Its still "Pm" not "PM."
Date above location is fixed.

**Comment by kaatvds** [comment]
some aspects of this ticket still need addressing: 

remove the orange title bars everyone. It works for Wayland but not for the other communities - - interferes with their branding. That is: on 
1. events on homepage
2. events on all events page
3. testimonial cards
Just make those the tile bars white, with the titles in black and bold (just like the event cards on the home page on prod right now: that is a nice, size and font - if that size and font could be uses for all titles, that would be awesome!

ALSO for event cards, It still says "Pm" it should say "PM."

**Comment by frimpongopoku** [comment]
Hi @kaatvds , making the title bar white makes the title sit on its own at the top, and it makes it look as if there is sooo much white space. What do you think of this instead? Just like the background of action cards?
![Screenshot 2020-11-04 at 11 35 35 AM](https://user-images.githubusercontent.com/26961591/98107211-16b5be00-1e92-11eb-97f8-b126351064d6.png)


![Screenshot 2020-11-04 at 11 35 35 AM](https://user-images.githubusercontent.com/26961591/98107211-16b5be00-1e92-11eb-97f8-b126351064d6.png)

**Comment by kaatvds** [comment]
Hi Frimpong. I really like how it looks on the home page on Prod right now:
![image](https://user-images.githubusercontent.com/30277868/98115709-3d193080-1e75-11eb-85ac-909b1d126506.png)
Can you just copy that?

**Comment by frimpongopoku** [comment]
What? Thats better??? Okay... 🤣  I will try to switch back to the old event cards, but it will definitely not be in the push I am preparing now. 

I need to look for the old events code so I dont have to write it again. lool

**Comment by kaatvds** [comment]
To be clear: not the old event cards o the All Events page, but the event cards on the HOME page...
