### ISSUE TITLE
DEV: new action card

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#367]
![Screenshot (705)](https://user-images.githubusercontent.com/30277868/95484106-0d523800-095e-11eb-8347-081adba7a1d0.png)

**Comment by kaatvds** [comment]
more info on the image: 

image doesn't get cropped but scaled to fit into red box = the available field = 16:9 - if pic is scaled 16:9 it will fill the red box, if not it is scaled and white space is added to the sides. Best practice for Cadmins will be to use 16:9 images r, if they like more white space, a different size but uniform throughout.

Text shortened to "Done" and "Info" so text remains same size but buttons are smaller (the 3 buttons should be the same size)
don't use icons on the buttons
card rounded on all corners
title bar just white with black text (so not like in screenshot below, but like in mockup in first comment)

![Screenshot (690)](https://user-images.githubusercontent.com/30277868/95769027-36880680-0c85-11eb-8548-fe3e21bca4de.png)

**Comment by kaatvds** [comment]
The card should be a frame around the picture, title + buttons.  Not just the frame around the picture and title. Just like the mockup.

The title should go the full width of the frame, with a font size which fits 40 characters covering the entire width.  Titles should be only one line, and additional space removed so 3 rows of cards fits on a page if possible.

Make the photo go full width for 16:9 photos, without cropping.  Narrower photos must have some white space added.  Don’t distort photos by squishing; if they are too wide crop the edges, if they are narrow there should be white space. As explained above.

On all actions page, a little less space for the main title, and a bit less space vertically between cards. We really want three above the fold.

“More” button should read “info” as on mockup

suggestions: 
The title bar: a light grey background
giving the outline of the cards a bit of green color

**Comment by apowelka** [comment]
![image](https://user-images.githubusercontent.com/60662056/96915739-a2802100-1474-11eb-938a-73247115b492.png)
I think this didn't get fixed all the way, the photos are at the top of the box

**Comment by BradHN1** [comment]
@frimpongopoku - Clicking anywhere on the photo or action title should get to the single action page.

**Comment by frimpongopoku** [comment]
Hi @apowelka , this is what will happen if  an admin does not upload an image with a 16:9 aspect ratio. Image will be centred and contained, with white space. If we force the images to fit all the way, the images will stretch! @kaatvds , and @BradHN1  have warned against that.

**Comment by frimpongopoku** [comment]
> @frimpongopoku - Clicking anywhere on the photo or action title should get to the single action page.

Oooops, incoming.....

**Comment by kaatvds** [comment]
as discussed on Slack, make sure the optimal image ratio - which fills the whole space and so gets rounded on left top corner  - is 16:9 (currently it looks like it is 18:9).

**Comment by kaatvds** [comment]
card and picture should retain aspect ratio - should not stretch with different window sizes.
the full-size pic should be 16:9 (wider gets cropped).

**Comment by frimpongopoku** [comment]
Hi @kaatvds, I am using percentages to determine how much space the content on the website should fill a user's screen. 
Meaning, the cards, and the whole screen will adjust according to how big or how small a user's screen is. 
So for the **cards**, I dont think it is a good idea to make anything fixed.  Unless you want the content to be fixed on the left side with a chunk of white space on the right when a user uses a big screen...? 🤣 🤣 🤣 

For the pictures.... I dont think I understand what you are saying... I thought I fixed the stretching?? May I please have a picture of what you are seeing?

**Comment by kaatvds** [comment]
I guess what I'm trying to say is that card and picture behave together, in the same way. Does that make sense?
We can slack if you want. Am mostly free today.

**Comment by kaatvds** [comment]
so, for instance, if you look at the first pic, at one screen size it looks like this:
![image](https://user-images.githubusercontent.com/30277868/98116005-ab5df300-1e75-11eb-9f31-105ff6503e6d.png)
At a bigger size, like this:
![image](https://user-images.githubusercontent.com/30277868/98116050-b9137880-1e75-11eb-8c6c-036e9559150d.png)

**Comment by kaatvds** [comment]
Frimpong and I discussed this and I think I understand the issue: making the ideal ratio  (which fills the whole space) for the pic 16:9 (instead of current 18:9) would require changing the aspect ratio of the whole card: make it higher. So let's leave it the way it is with 18:9 as ideal ratio.
I will reach out toe @Sam about whether it is possible (whether now or later) to enforce that aspect ratio when the cadmin uploads the image when making the Action on Cadmin - then we won't need a third party service/site for that.
