### ISSUE TITLE
Actions: Requesting 4th tab in indiv Action page

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#37]
tab on indiv action page (next to description, steps and testimonials) called "deep dive" would be great! That's where all the details can go.

**Comment by BradHN1** [comment]
also, or alternatively, a tab called "Impact" for calculator aligned actions could be used to ask the questions the calculator would use to estimate impact.  Need to talk this throug

**Comment by kaatvds** [comment]
that could be incorporated later. For now a simple fourth "deep dive" tab would be great since some folks will want more details while others just want the rough outline and pitch, and for the latter the details make for too log a text, especially on the phone.

**Comment by BradHN1** [comment]
I suggest that the 4th "Deep Dive" tab should only be present for actions where there is Deep Dive text.  Most actions won't have this and better to not burden community admins with having to provide it.

**Comment by kaatvds** [comment]
That sounds good!

**Comment by kaatvds** [comment]
@Frimpong made this happen by as we don't have Cadmin capability yet to enter content into fourth tab we can't test it. And so we should not push this until Cadmins can do this
