### ISSUE TITLE
DEV: teams - edit teams broke

### ISSUE THREAD

**Issue by apowelka** [massenergize/frontend-portal#374]
Edit teams - ability to change photo/logo is broken. PC/chrome.

Two different errors depending on which photo I tried to upload:

 Field 'id' expected a number but got 'undefined'.
 TypeError: Failed to fetch

Editing tagline get this error:  Field 'id' expected a number but got 'undefined'.

**Comment by BradHN1** [comment]
Fixed in branch BHN-teams-bugs

**Comment by kaatvds** [comment]
![image](https://user-images.githubusercontent.com/30277868/96187043-57ad5900-0f0a-11eb-9dfc-57db35846931.png)

**Comment by kaatvds** [comment]
this the editing worked. But then when the page loaded it says on top in dark red: "Team awaiting approval from Community Admin. Only team admins can access this page, via its direct URL or the teams listed on your profile page."
Why is that there? Does every edit to a team by a team leader need approval from the Cadmin?
![image](https://user-images.githubusercontent.com/30277868/96282675-01dbbe00-0fa9-11eb-8024-73817bc1d494.png)

**Comment by kaatvds** [comment]
I don't know what's going on here: I tried to "approve" this team to unlock it in cadmin and I don't get te form, only the list for the members.....

**Comment by BradHN1** [comment]
Fixed in portal to keep team live.

**Comment by apowelka** [comment]
Sees preview of new photo but does not save. crop forces it closed. editing text is fine.

**Comment by BradHN1** [comment]
I was able to edit a team (TDS Support Group in Nowhere) and change the photo.  The interface could be improved but it works and is much better than currently in prod.

**Comment by apowelka** [comment]
got the photo save to work, I wasn't able to successfully use the crop correctly yesterday and that caused me issues. Taking a re-look with the knowledge that it worked for Brad, I saw how to work the crop and then I could save the photo.
