### ISSUE TITLE
DEV: Filter on action tags - testimonials needs rethinking

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#382]
In Wayland, the "testing 10/15" testimonial is tagged as transportation but it shows up under solar
![image](https://user-images.githubusercontent.com/30277868/96171237-a0591800-0ef2-11eb-9d73-19822bafebbf.png)
and not under Transportation
![image](https://user-images.githubusercontent.com/30277868/96171280-af3fca80-0ef2-11eb-9ecf-b828987aec28.png)

**Comment by BradHN1** [comment]
Question on Testimonial filtering: on the case you pointed out in issue 382, the testimonial is linked to an action (Frimpong’s new action) which has the tags SolarPV and Home Energy.  But the testimonial has a tag “Transportation”.  That is an odd case.  Should testimonials even have tags independently of the actions?
2:50
I can make it ignore the action tags.  Users don’t put in the tags, and the cadmin does, so if we leave it as is the filtering will be on the action tags.

**Comment by kaatvds** [comment]
Yes ,that would work
