### ISSUE TITLE
DEV: All action page: not have "more" and "pages": all on one - and position of filter box

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#383]
not have "more" and "pages": all on one 
move up the left column with “Filter by…” at left

**Comment by frimpongopoku** [comment]
Hi @kaatvds , could you please explain this? Thanks.  🤣

**Comment by kaatvds** [comment]
Yes, as predicted people don't like the 6 actions (and same for testimonials) per screen. It esp doesn't work when one is signed in and the TO DO and Done lists are displayed: those make the page long and then there is tons of white space under the 6 actions cards displayed.  o on ALL Actions page: show all actions, to scroll down.

The filter box could be bumped up against the bottom of the top menu bar. There is a LOT of prime real estate that is blank because of the "Actions" title: let's tighten that up:

![Uploading Screenshot (718).png…]()
