### ISSUE TITLE
Click Done to undo doesn't work on single action page

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#389]
This functionality work on the all actions page but not the single action page.

**Comment by apowelka** [comment]
Can't change an Action from Done to To Do on either All Actions page or Individual Action page. Get this error message, "Can't use the feature, you have already doen the action."

**Comment by BradHN1** [comment]
That is the correct specified behavior.  You can undo the action by clicking on Done, then add it to Todo.  If we want to change the spec we can do that in another ticket.

**Comment by kaatvds** [comment]
The single action page done etnd to do buttons are too small.
Also when I move my cursor over one the popup blocks my ability to click it.
![image](https://user-images.githubusercontent.com/30277868/97899915-f0641700-1d07-11eb-92c9-9cc4984853be.png)

**Comment by kaatvds** [comment]
connected to #423

**Comment by kaatvds** [comment]
Closing bec  same as #423
