### ISSUE TITLE
DEV: leave testimonial form doesn't fully reset 

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#391]
Which action is this about
and
pic
don't reset

SO when i want to fill in another one without a picture, let's say after filling one in WITH picture, I can't get rid of that old picture

**Comment by apowelka** [comment]
![image](https://user-images.githubusercontent.com/60662056/96916970-44ecd400-1476-11eb-8d48-eeb7b5c1c2b3.png)
Nope - you can load a new image and it shows on the submittal page. After clicking approve as an Admin, the photo  is replaced with the pre-existing testimonial's image.
