### ISSUE TITLE
DEV: Testimonial Image Preview and Cropping #390

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#393]
"We are sending now" runs forever probably because of HUGE picture: better for a warning to say: picture too big (if that was the issue.
![Screenshot (728)](https://user-images.githubusercontent.com/30277868/96204469-63ad1100-0f32-11eb-826c-13491ddd63aa.png)

**Comment by apowelka** [comment]
Tested on Thur 10/22. Does not get stuck, but there is no preview when you click "Crop." It simply saves the photo.

**Comment by apowelka** [comment]
so, it does work, its just not intuitive. close this ticket and open a new one to improve cropping

**Comment by kaatvds** [comment]
agree: not intuitive: would be great
