### ISSUE TITLE
Show the draft testimonial for the user who created it (marked as draft) so they can edit

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#400]
If a user has submitted a testimonial which is not yet approved by the cadmin, allow the user to see it on the site, so they can edit it and remember what they submitted.

**Comment by dim505** [comment]
@frimpongopoku I'd like to work on this. Just checking whether if you already have fixed it?

**Comment by frimpongopoku** [comment]
You can go ahead with that @dim505 👍🏾 😄
