### ISSUE TITLE
CAN: Teams and sub-teams relationship

### ISSUE THREAD

**Issue by apowelka** [massenergize/frontend-portal#408]
I tested in JCAN.

I joined 2 sub-teams, Earthworms and Havurahniks. I see my name on those teams, so far so good.

Going back to the Teams page, however, I see this message: 
![image](https://user-images.githubusercontent.com/60662056/97604833-4b35ff80-19e4-11eb-853c-b6daec35a12f.png)

I checked through all the other teams. I found that somehow I became a member of the MIT team but none of the others. I never joined the MIT team. Therefore, I also cannot leave this team that I have erroneously been assigned to.
![image](https://user-images.githubusercontent.com/60662056/97604917-699bfb00-19e4-11eb-9f1b-5dd70596be53.png)

**Comment by kaatvds** [comment]
I think this is solved
