### ISSUE TITLE
PROD: Cannot create a team

### ISSUE THREAD

**Issue by apowelka** [massenergize/frontend-portal#410]
cannot create a team or sub-team in JCAN with or without a parent. Also tried in Energize Framingham. Seems like the "Create" button isn't working. Confirmed that no teams came into CAdmin.

**Comment by BradHN1** [comment]
Fixed in portal branch BHN-fixes

**Comment by ellentohn** [comment]
when creating a team as logged in user you get stuck when hit "create button' -- 

See this panel -- happened in safari 

<img width="542" alt="Screen Shot 2020-10-31 at 11 53 33 AM" src="https://user-images.githubusercontent.com/60329553/97783723-ff17c600-1b6f-11eb-8822-97f0fd02f5ca.png">

**Comment by ellentohn** [comment]
I was able to create a team NOT associated with a parent team -- but the email I got as the cAdmin asking me to approve it send me to the dev site page - which was blank -- I think we need to fix the text in the email that goes to the Cadmin with the proper link to the page to approve --see below -
<img width="689" alt="Screen Shot 2020-11-01 at 8 39 46 AM" src="https://user-images.githubusercontent.com/60329553/97804475-380e7400-1c1e-11eb-856f-a978bb52c60a.png">

**Comment by jkatofsky** [comment]
Is this issue resolved? @BradHN1

**Comment by BradHN1** [comment]
Yes, this is resolved

**Comment by kaatvds** [comment]
But team creation email to user who created it leads to dev site. and on the canary when refreshing the page to see that team after cadmin approved  it  creates infinite loop = #244

**Comment by kaatvds** [comment]
testing CAN 1/31: after creating team (as subteam): blank page
![image](https://user-images.githubusercontent.com/30277868/151869967-bd42cc2e-df94-405b-bf86-70f6b7ff5694.png)

**Comment by kaatvds** [comment]
PROD: the CREATE TEAM button has disappeared.
