### ISSUE TITLE
Teams and subteams: if in one subteam not another: how to order on page

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#416]
If member of a team but member of only 1 subteam (of many), how can user see what subteam they are in: All the subteams are shown above the line ("Other teams").

Can we somehow make clear which sub teams they are a member.

How about: show the subteams they are a member of op top with a green check mark. Then a line (within this team) that says "you are not a member of these subteams").

SUggestions welcome!

**Comment by jkatofsky** [comment]
The solution that was agreed upon: maintaining the current organization of the teams page, and including in the teams cards the "in team" or "in team via sub-team" green text/check mark which lives to the right of the team title on the single team page
