### ISSUE TITLE
on profile: click "view all teams" > blank

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#419]
![image](https://user-images.githubusercontent.com/30277868/97729664-50a94d80-1aa9-11eb-907d-06d3cd6f1682.png)

**Comment by BradHN1** [comment]
I have tried to observe this bug, but can't manage to do so.  
@kaatvds - if you can make it happen and share a screen, that would be helpful, otherwise I have to assume it is a network glitch.
