### ISSUE TITLE
Single action page - Button size inconsistent

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#423]
Keep ToDo Done button sizes consistent, like on all Actions page:
![Screen Shot 2020-10-31 at 8 23 17 AM](https://user-images.githubusercontent.com/12800484/97779138-9cfc9800-1b52-11eb-94bd-8bc1aa73a4dc.png)

**Comment by kaatvds** [comment]
Also, when I move my cursor over one the popup blocks my ability to click it.
![Screenshot (761)](https://user-images.githubusercontent.com/30277868/97912569-f9aaaf00-1d1a-11eb-8d6f-f3c53cd174fe.png)

**Comment by kaatvds** [comment]
after fixing this we need to test #389: whether undo button works or not - not testable at the moment

**Comment by kaatvds** [comment]
when clicking Done or TO do button the buttons still "jump"
