### ISSUE TITLE
CAN: no option for "remove" from "to do" list in profile

### ISSUE THREAD

**Issue by apowelka** [massenergize/frontend-portal#443]
testing asks us to remove an action fromt he to do list on the profile page. there is no way to do this.

**Comment by kaatvds** [comment]
Hi Aimee, this works for me. Can you check again?

**Comment by apowelka** [comment]
here is what I see 
![image](https://user-images.githubusercontent.com/60662056/98568111-bacaab00-227e-11eb-8f55-b2cc865cd798.png)

**Comment by kaatvds** [comment]
the issue is that the only way to remove something from TO DO, you have to have Done it.
To be addressed after deploy Can>Prod
