### ISSUE TITLE
CAN: must have unique team members

### ISSUE THREAD

**Issue by apowelka** [massenergize/frontend-portal#446]
Hi - I got a pretty rare situation, but I think it may be an easy fix. I tried to join a team as another user profile but with the same preferred name. I was not allowed to join a team. I got two separate error messages:

TypeError: Invalid attempt to spread non-iterable instance. In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
duplicate key value violates unique constraint "team_members_and_admins_team_id_user_id_efb0effe_uniq" DETAIL: Key (team_id, user_id)=(40, a1b1baa5-d106-450a-9266-b6885c988985) already exists.

I think we could fix this by changing language to, "another user by that name is already on the team. Please modify your preferred user name."

Actually, when writing this, we should probably implement this at the community level, not the team

**Comment by BradHN1** [comment]
@apowelka - I have looked at this, and I think the bug you encountered may have been something different, that you the browser got confused about which profile you were signed in as.  That can happen if you have another tab that you use to sign into the admin portal.  The error which produced the message was that the same user profile tried to join a team it was already a member of.  
However you do raise a good point, which is that perhaps we shouldn't allow multiple users in a community to have the same preferred name.  If they do, it will cause problems when it becomes possible for users to communicate with others .  It is a bit tricky, for the following reason.  When you create a profile signed into a community, it can easily check whether your name is unique.  Later, when the user joins another community, there is the possibility of a name collision. We could sometimes solve this by appending the users town name (not community name) to the preferred name (Brad-Concord) when on any community that isn't the community for that town.  Have to think about the best way to do this if we don't want to restrict users on the platform to unique preferred names.
