### ISSUE TITLE
in  DEV: registration  fix doesn't work - stuck in "sign in" loop 

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#45]
sadly the fix didn't work. I created new account,  i DID get an email.  I clicked on link and it DID open a new tab with a box and Continue Button:
![image](https://user-images.githubusercontent.com/30277868/73799237-5fb1d800-4783-11ea-820b-05b8571cad1d.png)
When I clicked that but that gave me this screen again:
![image](https://user-images.githubusercontent.com/30277868/73799255-71937b00-4783-11ea-926c-f6a2a8c1b6e3.png)
Then I clicked sign in again and it sent me back to:
![image](https://user-images.githubusercontent.com/30277868/73799282-896aff00-4783-11ea-9c3f-86b763bfdd32.png)
I clicked sign in, and round and round.

and when I clicked

_Originally posted by @kaatvds in https://github.com/massenergize/frontend-portal/issues/39#issuecomment-582181827_

**Comment by kaatvds** [comment]
just want to make sure this doesn't get pushed to prod bec in prod it works better.

**Comment by BradHN1** [comment]
It appears that registration works correctly for standard e-mail addresses, but not for an address like "name+1@gmail.com".  That may sometimes work, but firebase doesn't seem to give the addresses with + proper authorization.
