### ISSUE TITLE
PROD: Testimonials don't turn up in Testimonials tab on Indiv Action page

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#462]
It only shows the testimonials submit form

**Comment by BradHN1** [comment]
THe testimonial partly shows up on the action page, without the photo.

**Comment by frimpongopoku** [comment]
Yes @BradHN1 , the photo will come soon. You know the issues with photos ... lol. Just wanted this to replace the current bug in PROD ASAP!

**Comment by BradHN1** [comment]
Seems to be fixed
