### ISSUE TITLE
PROD: error message trying to visit homepage from portal 

### ISSUE THREAD

**Issue by mlevy21** [massenergize/frontend-portal#466]
-when clicking on the button "MassEnergize," you are not taken to the homepage but an error message comes up instead 
<img width="1440" alt="Screen Shot 2020-11-16 at 9 47 45 AM" src="https://user-images.githubusercontent.com/71030438/99266638-f7535500-27f0-11eb-83f0-70b523be2851.png">

**Comment by BradHN1** [comment]
Fixed in BHN-fixes
