### ISSUE TITLE
Prod: contact us form doesn'twork

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#467]
I filled in fields, pressed "send message", nothing happens.

**Comment by kaatvds** [comment]
![image](https://user-images.githubusercontent.com/30277868/99579123-c1a69b80-29ab-11eb-95ea-4f46cb34e6e5.png)

**Comment by kaatvds** [comment]
The above was a prob for a not-signed in user
.I signed in and then the form worked (and I got the notifcation). 
SO: one needs to be signed in in order to send contact form? = bug

**Comment by frimpongopoku** [comment]
@Opoku-Agyemang , @BradHN1

**Comment by frimpongopoku** [comment]
@kaatvds  you are getting the hang of these error messages! Very soon, you will be coding your own changes 🤣 🤣 🤣 🤣!

**Comment by BradHN1** [comment]
Trivial fix, I added it to my API branch which has an open PR.
