### ISSUE TITLE
PROD: Testimonials Capitalize Every Word

### ISSUE THREAD

**Issue by apowelka** [massenergize/frontend-portal#468]
Hi - I have a very minor bug to report. On the Testimonials, the preview page seems to Capitalize Every Word In The Description. This does not happen within a testimonial. https://community.massenergize.org/Framingham/testimonials
Pc/Chrome:  https://massenergizecommunity.slack.com/files/UR4A08EQY/F01EXLNJCKY/image.png

**Comment by kaatvds** [comment]
Same happens in Events, by the way -  will create extra ticket?
