### ISSUE TITLE
Testimonial without associated action

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#47]
ISSUE 1022
Reported on Mon Nov 11 2019 16:21:30 GMT-0500 (EST)
Reported by Bradley Hubbard-Nelson(brad@massenergize.org)
PRIORITY = 
STATUS =  - Deferred 

Site Url: http://community-dev.massenergize.org/erehwon/testimonials

Description:
At this point you need to have an action defined for a testimonial. I think it should be possible to have a testimonial which can be associated with 0,1,or more actions

Notes: deferred

**Comment by kaatvds** [comment]
works in dev but  reopening due to new validation procedure
