### ISSUE TITLE
can't go straight (cold) to a team page

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#480]
I pasted the link  https://community.massenergize.org/wayland/teams/33 into a Facebook post.  Facebook seems to add something to the url and then that page gets hung up. Let's look at this when we meet in 10? 
![image](https://user-images.githubusercontent.com/30277868/101185087-70d7a980-361f-11eb-9bd2-67583f115759.png)

**Comment by kaatvds** [comment]
Hi Frimpong, does this issue also have to do with these long links for teams on our Google Analytics report (I'll slack it to you

)?
If you can deal with this issue soon that would be awesome!

**Comment by frimpongopoku** [comment]
Nope! 🤣 , I dont think so. I have some time tomorrow, I will check out what is happening and keep you updated. 😺 @kaatvds
