### ISSUE TITLE
All communities page enhancements

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#482]
If more than six communities (which there are), select the communities from a dropdown menu rather than buttons on the page.  

Default on the dropdown menu could be the last community you visited;

“Search” is first option on the dropdown, which could use a modal to search by city/state, organization, or group name.
Search could take zip code to find nearest communities, or community and state.

**Comment by BradHN1** [comment]
Additional thought - can use IP address to put the local community first in the dropdown menu.

**Comment by BradHN1** [comment]
Great work!  I'd like to suggest removing the "Most Visited" section, and change the text to "Select Your Community or visit any community site"  (since some people won't have their community on the list).

Change "Go To Our Main Site" to "Find Out More About MassEnergize and Starting Your Community Site"

On the pull down list, change each entry to "Location - Community name" (for Geographic communities), where Location is "Town, State".  Non-geographic communities just the Community Name.  Then order alphabetically by the entry.  For example, Sustainable Milton would be "Milton, MA - Sustainable Milton".

**Comment by frimpongopoku** [comment]
Noted @BradHN1 .

**Comment by kaatvds** [comment]
I see Brad had already put these requests in - I will copy my mockup below and delete #579 
![Screenshot (1005)](https://user-images.githubusercontent.com/30277868/120022461-6f79af00-bfba-11eb-85c5-a1ad3b2ce878.jpg)
