### ISSUE TITLE
We used to have RSVP for events: it's gone

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#53]
ISSUE 1157
Reported on Mon Dec 09 2019 15:33:42 GMT-0500 (EST)
Reported by MassEnergize(KAATvds@gmail.com)
PRIORITY = Medium
STATUS =  - Submitted 

Site Url: http://community-dev.massenergize.org/wayland/events/84

Description:
We used to have RSVP for events: can we have that back? It also used to be displayed on user profile under TO and Completed: can we have that back?

User Role: Community User

**Comment by kaatvds** [comment]
closed because in #80
