### ISSUE TITLE
Multiple filters should be more filtering (logical AND, not OR)

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#532]
This applies to the new horizontal filter as well as the old left panel.

If you choose "Home Energy" the actions involving home energy are shown.

If you then choose "High impact" the actions involving BOTH home energy AND high impact are shown.

Currently it is working as OR.

**Comment by kaatvds** [comment]
I guess we can't do: I am a homeonwner AND I live in a condo, or: I am interested in home energy AND transport (that, is choose two option in one category)?  That would mess up the filter again... but let's keep looking for solutions after this big  overhaul :)

**Comment by BradHN1** [comment]
Pleas not
