### ISSUE TITLE
Implement the Profile Picture

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#534]
The backend UserProfile model allows for a profile picture. 
Implement the taking of or uploading of a profile photo from the initial profile screen and the edit profile screen.

The cropping should be to a circle, resolution comparable to what Github has.

Show this profile instead of the green button when the user is signed in.

For profiles without a photo, create one on the fly with a circle, colors randomly chosen, with the users initials in capital letters.

This pic will be used in many places, such as teams and news, and when we allow user-user communication.

We could give prizes for most interesting profile picture.

**Comment by BradHN1** [comment]
Good work.  A few changes to discuss.
My thoughts on profile button and menu, would like @kaatvds input.  Before signing in, the button is an oval:
<img width="532" alt="Screen Shot 2021-06-17 at 7 34 28 AM" src="https://user-images.githubusercontent.com/12800484/122389530-05ac4f80-cf3f-11eb-9d51-2dbc5163fb87.png">

(comment - I've zoomed in to the size where the font on the menu is readable to me, we may want to increase it)
With the code I tested, when you sign in the profile button is a different shape (not circular):
![Screen Shot 2021-06-17 at 7 40 12 AM](https://user-images.githubusercontent.com/12800484/122393387-d3045600-cf42-11eb-9e12-4e91da65157c.png)

My thought is the button could stay an oval - same size as before sign-in, with the circular button inside on the left, and the word "Profile" to the right of it.  I'm not sure how the color would look.  I think it shouldn't be green when signed in, but a dark outline, with the word Profile in colored text.

**Comment by tzheng56** [comment]
Photo upload successfully but looks more like an oval than a circle -- looks stretched out

**Comment by BradHN1** [comment]
Edit profile needs some fixes, including the ability to delete the profile picture, and view and set the color of the default (initials) profile button.  Here is what it looks like now:
![Screen Shot 2021-08-20 at 9 16 12 AM](https://user-images.githubusercontent.com/12800484/130239262-5e5faf6f-bc0f-458f-9277-d4ac353d7f1a.png)

**Comment by kaatvds** [comment]
doesn't seem to work

**Comment by vaaranan-y** [comment]
Whenever a user tries to upload their own profile picture, they do not get a preview, instead they get this:
![image](https://user-images.githubusercontent.com/69359660/132915735-7356139a-b8c3-4d8b-87ac-8b7649138c64.png)
However, the profile is still successfully updated when the user presses submit.

**Comment by nenadev21** [comment]
Passed. The only issue is that isn't possible to crop an image. The profile takes the full image uploaded even when cropped. I'll create a separate card for that

**Comment by Davidjwkinghorn** [comment]
This should be fixed now.
