### ISSUE TITLE
Implement GHG equivalences

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#535]
Once the Equivalences model and routes implemented in the API ([Ticket #248](https://github.com/massenergize/api/issues/248))

Profile page - choose whether GHG equivalences should scroll (every 5 seconds), or pick one to stick with.

Cookie on browser can save this setting.

The chosen equivalence and scrolling should operate on the home page (community GHG), profile page (personal GHG), team pages (team GHG) and Actions page.

**Comment by frimpongopoku** [comment]
Noted @BradHN1

**Comment by BradHN1** [comment]
Carbon equivalency on home and impact page donuts implemented together with issue #687, PR #688

**Comment by nenadev21** [comment]
Passed. The browser saves settings and they are displayed where expected. 
However, if a user signs out of the page, settings regarding equivalences are lost. I'll create a card to find a way to store this setting on the user's profile.
