### ISSUE TITLE
Donation link doesn't update

### ISSUE THREAD

**Issue by ahasha** [massenergize/frontend-portal#549]
I provided an updated donation link through the cadmin portal for the sustainablemilton community, but when I visit the donate page in the sandbox website it still takes me to massenergize's paypal.  

The site is not yet live, so I am testing in the sandbox.

You can see the donation page [here](https://sandbox.community.massenergize.org/sustainablemilton/donate)

The donate button goes to: https://paypal.me/massenergize?locale.x=en_US

The donation link I provided in the cadmin interface was: https://www.sustainablemilton.org/one-time-donation-pay-pal

**Comment by ahasha** [comment]
@BradHN1, do you know who can help with this?

**Comment by frimpongopoku** [comment]
Hi @ahasha , your link is safe, and this bug  does not actually exist anymore. Sandbox is currently just running on old code that is why. As soon as @BradHN1 publishes the new changes to the sandbox portal, you will see your link changes reflect 🤗

**Comment by ahasha** [comment]
I actually took the site live a few weeks ago and the donate button still goes to the MassEnergize paypal on the live site.  Should I update the donation link again to get it to update?

**Comment by kaatvds** [comment]
In canary the donate button doesn't update either... Created #586
