### ISSUE TITLE
home page/phone view/layout issues

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#55]
ISSUE 1167
Reported on Tue Dec 10 2019 08:55:06 GMT-0500 (EST)
Reported by Ellen Ellen Tohn(ellentohn@gmail.com)
PRIORITY = Medium-High
STATUS =  - Submitted 

Site Url: http://community-dev.massenergize.org/wayland/

Description:
When accessing the home page using my phone the logo on the top left is cut off, the home page has too much white space after the donuts before the all impact button , and all events button is not centered. And for impact page, I think it we can make the donuts smaller that would be ideal for the phone and the impact graphs are too small on the phone-- it would be good to show the actions graph

User Role: Community User
Notes: 4 this remains an issue for some users... cf issue #1190

**Comment by kaatvds** [comment]
reopening (cf. new Project procedure on Github for validating bug fixes)

**Comment by kaatvds** [comment]
![image](https://user-images.githubusercontent.com/30277868/74940184-125a7b00-53bf-11ea-900f-b51fff392f36.png)

**Comment by kaatvds** [comment]
@Pongo1 let's talk about this one

**Comment by kaatvds** [comment]
This ticket now gathers previous tickets to do with the layout. The platform looks great on a large screen but there are still issues when the user's screen is set to less than 100% and especially when looking on phone. @pongo you and I should arrange some Slack time to talk about these.
Older tickets under this one:
#70, #36, #46, ...
I am removing those tickets from the Board

**Comment by ellentohn** [comment]
This is a duplicate for #116 so I think we can delete it?

**Comment by ellentohn** [comment]
just tested on DEV on iphone it works for me @kaatvds can you test on other type of phone

**Comment by kaatvds** [comment]
It always worked on Ellen's phone, but the same issues recur on my motorala. Screenshots:

![Screenshot_20200316-180626](https://user-images.githubusercontent.com/30277868/76803951-6afc1880-67b1-11ea-9aa9-afba5bce23ef.png)
![Screenshot_20200316-180653](https://user-images.githubusercontent.com/30277868/76803959-6fc0cc80-67b1-11ea-90e5-9bb12076da0e.png)

**Comment by kaatvds** [comment]
The misalignment on my Motorol
![Screenshot_20200327-111445](https://user-images.githubusercontent.com/30277868/77771087-9fc36780-701c-11ea-8430-8e3d7954ed69.png)
a is not fixed:

**Comment by kaatvds** [comment]
this is fixed on motorola
