### ISSUE TITLE
Unable to sign in through Google on IPhone

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#566]
Using IPhone, safari browser, on Canary

Tried to sign onto the community portal via google, and I get stuck on a page with no text on it.  I think it is a firebase redirect.

**Comment by BradHN1** [comment]
@frimpongopoku could not replicate, but it happens to me regularly.
When I sign in from google I get message "Unable to establish a connection with the popup.  It may have been blocked by the browser"

**Comment by Davidjwkinghorn** [comment]
Closing old issue.
