### ISSUE TITLE
let testimonial author leave a name

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#57]
ISSUE 1174
Reported on Fri Dec 13 2019 15:20:17 GMT-0500 (EST)
Reported by Kaat Vander Straeten(KAATvds@gmail.com)
PRIORITY = High
STATUS = InProgress - Submitted 

Site Url: http://community-dev.massenergize.org/wayland/testimonials

Description:
When authoring a testimonial, have extra field "How would you like your name to be displayed, e.g. 'John Doe' or 'Anonymous in Wayland'

User Role: Community User
Notes: cf. issue 1210

**Comment by kaatvds** [comment]
closed because in #78
