### ISSUE TITLE
Tell testimonial author their name will  be known to Cadmin

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#58]
ISSUE 1175
Reported on Fri Dec 13 2019 15:23:35 GMT-0500 (EST)
Reported by Kaat Vander Straeten(KAATvds@gmail.com)
PRIORITY = High
STATUS = InProgress - Submitted 

Site Url: http://community-dev.massenergize.org/wayland/testimonials

Description:
connected to issue 1174: "How would you like your name to be displayed, e.g. 'John Doe' or 'Anonymous in Wayland'" should actually read: "Your name and email will be shared with the community organizer but will not be shown. So how would you like to publically sign off on this testimonial? For instance, 'John Doe' or 'Anonymous in Wayland'?"

User Role: Community User
Notes: cf. issue 1210

**Comment by kaatvds** [comment]
closed because in #78
