### ISSUE TITLE
in footer: change "click to email commmunity organizer" to "Click to contact Community Organizer"

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#587]
And replace . the email icon with a question mark for instance.
(because it doesn't go to email but to the form)

**Comment by BradHN1** [comment]
Agree with "contact"; the icon is fine I think

**Comment by BradHN1** [comment]
thought I had fixed this but it only got into Canary.  Doing it again

**Comment by BradHN1** [comment]
Fixing this for good this time.
