### ISSUE TITLE
In footer: instead of "Click to email admin" write "Click to email community organizer"

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#59]
ISSUE 1177
Reported on Fri Dec 13 2019 15:57:49 GMT-0500 (EST)
Reported by Kaat Vander Straeten(KAATvds@gmail.com)
PRIORITY = Medium-High
STATUS =  - Submitted 

Site Url: http://community-dev.massenergize.org/wayland/

Description:
In footer: instead of "Click to email admin" write "Click to email community organizer"

User Role: Community Admin

**Comment by ellentohn** [comment]
I did not see this change when I looked on https://community-dev.massenergize.org/wayland -- is it on another site? @Pongo1 @BradHN1

**Comment by Pongo1** [comment]
Hi @ellentohn, it has been fixed. I just havent made it live yet. I want to pack a lot of enhancements and bug fixes together, before I make them live. Thats why, but it has 😄

**Comment by ellentohn** [comment]
Got it

The challenge for us is figuring out how we test the fixed items on the dev site. Before moving to prod. So it sounds like we need to wait to u indicate a deployment to Dec before testing   Is that correct?

Thanks

Ellen 

Ellen Tohn

**Comment by kaatvds** [comment]
this is fixed on DEV but Am reopening (cf. new Project procedure on Github for validating bug fixes)
