### ISSUE TITLE
Impact page - big graph makes text look dumb

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#593]
The graph was made larger, and text area too small, with memer list way at the bottom.  Make graph take 50% horizontal on laptop.  On mobile, IMO description should be before the graph

<img width="881" alt="Screen Shot 2021-06-01 at 3 41 46 PM" src="https://user-images.githubusercontent.com/12800484/120381090-006cc500-c2f0-11eb-8c0e-9cfc0e86ca0a.png">

**Comment by nenadev21** [comment]
Passed. It looks good on laptop and mobile
