### ISSUE TITLE
Mobile - contact team admin modal, can't scroll to Send button

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#606]
On mobile device the modal extends past end of screen.  Add scrolling on message, fit modal  to the screen.

**Comment by BradHN1** [comment]
See [https://drive.google.com/file/d/1AqZ-rkhBzfQIE6qJPNI1jLMgwD4X-Ijl/view?usp=sharing](https://drive.google.com/file/d/1AqZ-rkhBzfQIE6qJPNI1jLMgwD4X-Ijl/view?usp=sharing)

**Comment by BradHN1** [comment]
On the mobile, I'd like to see the Send button larger and centered on screen.
Also I can't easily read the text "Thanks for contacting" because the font is too small.   I think that text should come in below the button, not above it.

**Comment by kaatvds** [comment]
Brad's comments seem addressed? Close this ticket?

**Comment by BradHN1** [comment]
Send and cancel buttons still too small and not centered.
