### ISSUE TITLE
In Indiv Action page, when hovering over grey (not signed in) TODO or Done it Buttons have a pop up saying, respectively,  "sign in or create an account to create a to do list" and  "sign in or create an account to let us know you've done it" same as on Action list

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#61]
ISSUE 1179
Reported on Fri Dec 13 2019 16:01:50 GMT-0500 (EST)
Reported by Kaat Vander Straeten(KAATvds@gmail.com)
PRIORITY = Medium-High
STATUS =  - Submitted 

Site Url: http://community-dev.massenergize.org/wayland/actions

Description:
In Indiv Action page when hovering over grey (not signed in) TODO or Done it Buttons have a pop up saying, respectively,  "sign in or create an account to create a to do list" and  "sign in or create an account to let us know you've done it". same as on Actions list

User Role: Community User

**Comment by Pongo1** [comment]
Hi @BradHN1  so, should the popups be removed? or should the text be changed. What should the fix be?

**Comment by kaatvds** [comment]
when not signed in - you hover over the grayed out to do and completed buttons on the actions list page, pop up says "sign in to..." ADD the same popups to the indiv actions page todo and completed buttons.

**Comment by kaatvds** [comment]
Looks good on DEV but  reopening (cf. new Project procedure on Github for validating bug fixes)
