### ISSUE TITLE
Testimonials card: need update

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#628]
photos cropped
no name on card
etc.
will mockup

**Comment by kaatvds** [comment]
The problem with the photo cropping is that usually when users submit a photo they take a vertical photo... Have to find a way around this

**Comment by kaatvds** [comment]
It looks fantastic!!!

**Comment by nenadev21** [comment]
Image looks good. 
About the second issue regarding the name, the community portal displays the full name on the profile instead of the "preferred" name submitted on the testimony
