### ISSUE TITLE
State-Reported Data not correct

### ISSUE THREAD

**Issue by apowelka** [massenergize/frontend-portal#631]
State reported data entered by CAdmin not displaying correctly on user portal under community impact (or in data download via CAdmin portal). Example: Wayland: 
![image](https://user-images.githubusercontent.com/60662056/125352441-44130f80-e32f-11eb-894a-5d5789d76ca7.png)

Documented: https://docs.google.com/document/d/17pT5swpC3C7J4zER006v7p2FczRCwt0EDO_c1-BMgIE/edit

**Comment by apowelka** [comment]
CAdmin Issue #368

**Comment by kaatvds** [comment]
same as Front end Admin #361
