### ISSUE TITLE
Why is template showing on EnWay?

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#636]
When I deleted the word TEMP from the title in the template (set as a template) it reflected that change on the wayland site.
![Screenshot (1080)](https://user-images.githubusercontent.com/30277868/126788388-a6968a3b-d118-4fef-b78e-799b81d7ea71.png)
![Screenshot (1081)](https://user-images.githubusercontent.com/30277868/126788390-77621ba7-95c3-4758-a872-721287f7a1e5.png)

**Comment by BradHN1** [comment]
I have looked to see whether this happens currently but don't see it.

**Comment by Davidjwkinghorn** [comment]
@kaatvds have you seen this again recently?

**Comment by kaatvds** [comment]
Haven't seen  it...
