### ISSUE TITLE
Add "do you want to recommend a vendor?" to Vendor page

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#64]
ISSUE 1185
Reported on Fri Dec 13 2019 18:39:06 GMT-0500 (EST)
Reported by Kaat Vander Straeten(KAATvds@gmail.com)
PRIORITY = Medium
STATUS =  - Submitted 

Site Url: http://community-dev.massenergize.org/wayland/services

Description:
Add "do you want to recommend a vendor?" to Vendor page

User Role: Community User

**Comment by kaatvds** [comment]
closed bec duplicate
