### ISSUE TITLE
Homepage pics still get cropped

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#640]
All the pics on EnWay are 4:3. When uploading the crop box shows them in their entirety. Yet on the homepage they are cropped on all sides. 
I am trying to add white strips on left and right of middle picture to get the picture defined better. With this cropping that won't work.

**Comment by Davidjwkinghorn** [comment]
Duplicate of [issue 288](https://github.com/massenergize/frontend-admin/issues/288)
