### ISSUE TITLE
on indiv vendor page, add "Do you want to recommend a vendor?

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#65]
ISSUE 1186
Reported on Fri Dec 13 2019 18:40:25 GMT-0500 (EST)
Reported by Kaat Vander Straeten(KAATvds@gmail.com)
PRIORITY = Medium
STATUS =  - Submitted 

Site Url: http://community-dev.massenergize.org/wayland/services/1

Description:
on indiv vendor page, add "Do you want to recommend a vendor?

User Role: Community User

**Comment by kaatvds** [comment]
dont't see the fix on dev

**Comment by kaatvds** [comment]
this works on portal but nowhere to see it on admin side

**Comment by kaatvds** [comment]
but that is being handled on admin side #28
