### ISSUE TITLE
text on donate page too light: additions are black

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#653]
The grey is - I think - are the default: it's too light.
And strangely enough my latest edits to that text come through in black.

![image](https://user-images.githubusercontent.com/30277868/131511257-461f7614-6b24-4200-bb6c-9ae8b74dd86b.png)

**Comment by nenadev21** [comment]
the donate button is gray and turns green when hovered. 
Looks fine for now but we can change it to green at the start and light red when hovered (similar to the "our impact" button) to make it more visible. I'll create a card for this.
New text added on description takes the same color (gray) which looks good.
