### ISSUE TITLE
on vendors, "Already used this vendor? Tell Us Your Story" is there twice

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#66]
ISSUE 1187
Reported on Fri Dec 13 2019 18:42:08 GMT-0500 (EST)
Reported by Kaat Vander Straeten(KAATvds@gmail.com)
PRIORITY = Medium
STATUS =  - Submitted 

Site Url: http://community-dev.massenergize.org/wayland/services/1

Description:
Delete "Already used this vendor? Tell Us Your Story" underneath the submit button in testimonial form - Same at bottom of leaving testimonial for an action ("Already completed this action? Tell Us Your Story")

User Role: Community User

**Comment by kaatvds** [comment]
That line is still there... so not sure what happened here...
