### ISSUE TITLE
Edit profile - change email, hangs

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#660]
Infinite circle hang, 
![image (2)](https://user-images.githubusercontent.com/12800484/132920421-73b4323f-6757-4161-a4fc-d2041ea2bf46.png)

**Comment by BradHN1** [comment]
The profile no longer works at all, even if you sign in again.
James got a verify e-mail, which he clicked and that fixed it.

**Comment by BradHN1** [comment]
The platform got stuck on me after updating my profile picture and refreshing the page.
Errors in javascript console:

(anonymous) @ instrument.ts:129
signin:1 Access to fetch at 'https://api-canary.massenergize.org/auth.whoami' from origin 'https://community-canary.massenergize.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
api-canary.massenergize.org/auth.whoami:1 Failed to load resource: net::ERR_FAILED
signin:1   Uncaught (in promise) TypeError: Failed to fetch
signin:1 Access to fetch at 'https://api-canary.massenergize.org/data.carbonEquivalency.get' from origin 'https://community-canary.massenergize.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
api-canary.massenergize.org/data.carbonEquivalency.get:1 Failed to load resource: net::ERR_FAILED
instrument.ts:129 TypeError: Failed to fetch

May or may not be related to the original issue.

**Comment by frimpongopoku** [comment]
Yeah this hanging is usually because the users do not verify their email.  

I have put a notification above the spinner when that scenario happens again, so that the user knows what is going on 
<img width="1792" alt="Screenshot 2021-09-27 at 13 17 29" src="https://user-images.githubusercontent.com/26961591/134880824-331f350d-ca3c-497b-8f58-7e1eba94e92f.png">

**Comment by nenadev21** [comment]
Working as described above. I'll create a different card to tweak a bit the notification message that currently shows up. At first, it was hard for me to understand what was going on, so users may get confused.
