### ISSUE TITLE
CAN: should carbon units on all actions page "blink" (re. Fuctiona testing sheet)? If so, they don't

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#670]

**Comment by kaatvds** [comment]
now it works. Not sure what changed.

**Comment by frimpongopoku** [comment]
Hi @kaatvds, when you go to the actions page, the carbon units switch up to different equivalences for you if you have not set a default unit yet. The blinking is the result of the  transition between one unit to the other. It goes away when you set a preferred choice on the profile page.

**Comment by BradHN1** [comment]
THe blinking happens if a user hasn't signed in, which it shouldn/t/

Also, the home page carbon donut should show the carbon equivalency both for goal and achieved value.

**Comment by BradHN1** [comment]
@frimpongopoku - the blinking still happens if user not signed in.
There is an error message in the console:

![Screen Shot 2021-09-28 at 8 23 26 AM](https://user-images.githubusercontent.com/12800484/135086559-e5e2e8ba-2dde-43c1-92ce-a50427647c98.png)

**Comment by nenadev21** [comment]
Passed. I don't see the carbon metrics card blinking for users who haven't signed in yet. 
I couldn't verify brad's comment though. ("home page carbon donut should show the carbon equivalency both for goal and achieved value"). I'll make a separate card for this second issue.
