### ISSUE TITLE
CAN: SuperAdmin: Can't create a new category

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#676]
seemed okay when  submitted and is retained on Admin side, but doesn't show up in  filters on all actions page

**Comment by BradHN1** [comment]
@kaatvds - it will only show up on filter if an action uses a tag in that category.  Is that the issue?

**Comment by kaatvds** [comment]
Of course! Duh!
I'll try it out witrh an action to confirm. For now close the ticket.
Kaat
