### ISSUE TITLE
footer - newsletter subscription

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#68]
ISSUE 1190
Reported on Fri Dec 13 2019 19:02:16 GMT-0500 (EST)
Reported by Kaat Vander Straeten(KAATvds@gmail.com)
PRIORITY = Medium
STATUS =  - Submitted 

Site Url: http://community-dev.massenergize.org/wayland/contactus

Description:
In  footer under newsletter signup boxes, replace "Your mail id is confidential" with "your name and email are confidential and intended solely for sending you our Newsletter".

User Role: Community User

**Comment by kaatvds** [comment]
Looks good on DEV but  reopening (cf. new Project procedure on Github for validating bug fixes)
