### ISSUE TITLE
Impact page bar graph data errors

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#680]
We have been plotting this as a stacked bar graph, with reported data assumed to be a subset of state data to avoid double counting.  If reported data > state data, this is clearly wrong and the subtraction we were doing doesn't happen, so the graph data are wrong.

Discussed with @apowelka - decided to display as a non-stacked graph so those two quantities are independent, without implying that they add up.  Then we don't need to worry about double counting.

**Comment by nenadev21** [comment]
Passed. Bar graph displays state/self-reported data separately and updates according to new actions added.
