### ISSUE TITLE
Donut graph visual improvements:  Headings, Units, Carbon equivalences

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#687]
This figure shows what is being done:
<img width="1039" alt="Screen Shot 2021-09-24 at 8 55 18 AM" src="https://user-images.githubusercontent.com/12800484/134677801-767dd637-1155-43a1-b8e3-59bc37b6d8c0.png">

Adding a short header to each graph, change the text below to show descriptive units and using carbon equivalencies.
Default carbon equivalency is hard coded to be "Trees" if not selected by a user.

**Comment by BradHN1** [comment]
@frimpongopoku - now donuts look bad on impact page:
![Screen Shot 2021-09-28 at 8 30 49 AM](https://user-images.githubusercontent.com/12800484/135087211-8c7526e0-8ab9-4617-8661-e8e1d8c1b41f.png)

**Comment by Davidjwkinghorn** [comment]
Donuts reverse progress after 100%. 114% looks like around 90%.

I think we should also display something fun to celebrate when a community reaches its goals, as long as it's not too annoying. It could be something as simple as a little image of a trophy at the center of the donut with "Congratulations [community name]!" and maybe a simple animation.  
 
![Screen Shot 2021-09-29 at 4 45 21 PM](https://user-images.githubusercontent.com/15150372/135346448-a4b0e91e-6a42-4805-bd0a-3b3f282ad040.png)

**Comment by nenadev21** [comment]
Donut graphs visual improvements look good on laptop. Passing this card. 
I'll create a separate card for the issue mentioned by David regarding how over accomplishments are displayed to review options.
