### ISSUE TITLE
In footer, change Copyrights © 2019 All Rights Reserved. Powered by MassEnergize

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#69]
ISSUE 1192
Reported on Fri Dec 13 2019 19:36:25 GMT-0500 (EST)
Reported by Kaat Vander Straeten(KAATvds@gmail.com)
PRIORITY = Medium-High
STATUS =  - Submitted 

Site Url: http://community-dev.massenergize.org/wayland/contactus

Description:
In footer, change "Copyrights © 2019" to "Copyright" (singular) and the link to MassEnergize in "All Rights Reserved. Powered by MassEnergize" should open in a new tab.

User Role: Community User

**Comment by kaatvds** [comment]
In footer, change "Copyright © 2019" to "Copyright  © 2020" the link to MassEnergize in "All Rights Reserved. Powered by MassEnergize" should open in a new tab.

**Comment by kaatvds** [comment]
not sure if 2019 should now read 2020?

**Comment by kaatvds** [comment]
Great this looks good on DEV but I will reopen (cf. new Project procedure on Github for validating bug fixes)
