### ISSUE TITLE
CAN (Mobile): Drop-down called "I am a..." doesn't open if something is typed on search bar. 

### ISSUE THREAD

**Issue by nenadev21** [massenergize/frontend-portal#692]
Steps: 
- Click the hamburger
- Select Actions - Actions
- Type something on the search bar (e.g. car)
- Without erasing it, click to see the first filter "I am a...". It won't open
- Click the filter called "category". Drop-down displays correctly. 
- Go back to the first filter and now it gets display

**Comment by nenadev21** [comment]
<img width="375" alt="Mass Energize 2" src="https://user-images.githubusercontent.com/69801600/135149231-40e6b266-2d38-4669-8228-2378267d6c4d.png">

**Comment by BradHN1** [comment]
When I test this it works fine.
