### ISSUE TITLE
Add data explanation dialog on Impact page

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#698]
Add a button or link on impact page "Explanation of Data";

The dialog should say (and we can update the text as needed):

Data shown in the impact graphs comes from two sources:

  1.  Data collected on the platform from community members who have taken actions;
  2. Data entered by Community Admins for reported actions from State or Partner databases, or from previous community programs.

On the Community impact totals (donut graphs):
1. The Actions Completed graph shows the sum of self reported and state/partner data. In some cases, there may be double counting
2. The Households Engaged is an estimate. Communities sum up self reported households, plus the number of actions completed in the category with the largest number of state/partner values, and added community engagement efforts (plus community specific campaign efforts)
3. The Caron Reduction graph (if shown) shows the estimated reduction for actions taken on the platform, which currently use Massachusetts averages for those actions.  It may also include estimated carbon reduction from reported State/Partner data or previous programs, if that is provided by the Community Admin.

**Comment by nenadev21** [comment]
This is live in CAN. Closing up
