### ISSUE TITLE
Unable to crop my profile image when uploading it. It takes the full image regardless

### ISSUE THREAD

**Issue by nenadev21** [massenergize/frontend-portal#702]

**Comment by BradHN1** [comment]
@nenadev21 - I tested this and the cropping seemed to work.  Possibly the process is confusing, you need to specify "crop image" below the picture, then select an area, then hit "Crop" button above the picture.  We can improve on this.
Let me know if you want to test it together.

**Comment by nenadev21** [comment]
yes @BradHN1 you are correct. I didn't see that button at first. Closing out
