### ISSUE TITLE
in testimonials (comm portal) the filter box is squashed

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#71]
ISSUE 1205
Reported on Tue Dec 17 2019 14:06:14 GMT-0500 (EST)
Reported by Kaat Vander Straeten(KAATvds@gmail.com)
PRIORITY = Medium
STATUS =  - Submitted 

Site Url: https://sandbox.community.massenergize.org/wayland/testimonials

Description:
Filter box  in testimonials (comm portal) is squashed into narrow format compared to Actions page. Can it be the same proportion as on Actions Page?

User Role: Community User

**Comment by Pongo1** [comment]
Hi @BradHN1 May I please see a picture what you exactly is happening? Cos it does not look squashed on my side

**Comment by BradHN1** [comment]
@kaatvds reported this issue, and I haven't seen the squashed filter box in testimonials.  She could perahaps reproduce it,  but it isn't a Sprint1 or yet a Sprint2 issue.

**Comment by kaatvds** [comment]
filter on actions page:
![image](https://user-images.githubusercontent.com/30277868/74574288-2f232880-4f51-11ea-8c0e-30dc9af86db5.png)
As you can see, the titles of the categories fit
Filter on testimonials page:
![image](https://user-images.githubusercontent.com/30277868/74574344-6abdf280-4f51-11ea-8fa8-59e405d409fb.png)
As you can see here the longer titles are cut in two > onto an extra line. Also, the size of the fond in the filters seems different.

**Comment by kaatvds** [comment]
sorry same thing happens on my screen...

**Comment by kaatvds** [comment]
After discussion Kaat-Frimpong 3/23: filter box i all actions = he one: same layout, same size fonts (just minus rent/own. etc)

**Comment by kaatvds** [comment]
it is not squished but it still has a different font size and color than the one on all actions page: please make as uniform/consistent as  possible: same font, font size, font color, line spacing, line dividers, etc.. (same in events = new ticket #150.)
