### ISSUE TITLE
Donuts reverse progress after 100%. 

### ISSUE THREAD

**Issue by nenadev21** [massenergize/frontend-portal#712]
This is from card #687. Donuts reverse progress after 100%. 114% looks like around 90%.

Idea: I think we should also display something fun to celebrate when a community reaches its goals, as long as it's not too annoying. It could be something as simple as a little image of a trophy at the center of the donut with "Congratulations [community name]!" and maybe a simple animation.

**Comment by BradHN1** [comment]
The minimal improvement to keep donuts from reversing progress after 100% is to have them max out at 100%.  I've implemented this, and here is what it looks like:
![Screen Shot 2021-11-04 at 2 03 29 PM](https://user-images.githubusercontent.com/12800484/140395041-b7e37551-9469-45f0-9d73-ea967c13afb5.png)
