### ISSUE TITLE
CAN - Button to download the bar graph file isn't visible when on mobile. Works different in laptop.

### ISSUE THREAD

**Issue by nenadev21** [massenergize/frontend-portal#719]
Works different in laptop. 
Unsure if it's expected that the button to download the bar graph as a file is expected on mobile. Right now mobile users can't see that option. Probably it makes sense to keep it as it is for mobile users.

<img width="1440" alt="Screen Shot 2021-10-15 at 2 42 27 PM" src="https://user-images.githubusercontent.com/69801600/137537037-e98c26f3-6cb7-4bc3-b96d-f1e62172e54b.png">

**Comment by BradHN1** [comment]
Downloading graphs on Mobile isn't a requirement
