### ISSUE TITLE
PROD: Community portal does not load on Safari for non-custom subdomain sites

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#728]
Using Safari 15.0 in case it makes a difference.

From communities page, selected different communities (Lexington for example) and there is an infinite spinner.
Only message in javascript console is the community name, no errors seen.

**Comment by frimpongopoku** [comment]
Also, all these work perfectly well in my safari thought 🤔 . 
My Safari is version `14.03`, and for some reason I dont have any update suggestions  to go to 15 🤔 . loooool

**Comment by frimpongopoku** [comment]
I see 🤣 🤣
