### ISSUE TITLE
Error message signing in with Google in Safari

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#733]
When I sign into the portal (any version) with Safari (version 15 or others) I get an error message:
<img width="751" alt="Screen Shot 2021-10-22 at 2 26 53 PM" src="https://user-images.githubusercontent.com/12800484/138504972-38cca7cc-275d-4978-97ee-00d157506fbc.png">

Workaround: if I then click the Google icon a second time, the popup appears, and can sign you in.

**Comment by Davidjwkinghorn** [comment]
Possibly a duplicate issue with [566](https://github.com/massenergize/frontend-portal/issues/566)

**Comment by BradHN1** [comment]
I agree - it seems to work fine now probably with a browser update.
