### ISSUE TITLE
Home page: Center when more than 3 event cards > center 

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#756]
Looks like the fourth card is no longer centered;
![image](https://user-images.githubusercontent.com/30277868/141159908-9892534c-88dc-491b-aa56-6ce625f9a26e.png)

**Comment by BradHN1** [comment]
The home page is made for up to 3 cards.  Need to think this through.  Perhaps with analytics we can see who clicks through the events on the home page rather than the events page.

**Comment by kaatvds** [comment]
It used to do this. At some point Wayland had 8 - and it centered the 7th and 8th nicely.

**Comment by BradHN1** [comment]
@frimpongopoku - is there a CSS fix for EventsHomePageSection.js which would fix this?

**Comment by kaatvds** [comment]
and... it no longer centers :( Reopening
<img width="940" alt="Screenshot 2022-11-11 at 7 56 49 PM" src="https://user-images.githubusercontent.com/30277868/201448835-525b77b7-50f7-4864-8550-b098172957c4.png">

**Comment by BradHN1** [comment]
Featured events on home page not centered properly:
<img width="1195" alt="Screenshot 2023-04-24 at 10 28 43 AM" src="https://user-images.githubusercontent.com/12800484/234028000-03c404db-030a-44b1-bb41-3d31e4142f31.png">
