### ISSUE TITLE
Eliminate Quick Links from footer

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#769]
I'm thing we can get rid of these.  i doubt anyone has ever used them, and they are available in the header, plus they would need to be fixed for the disabled pages.  WIth the exception of privacy policy and terms of service

![Screen Shot 2021-11-19 at 4 58 12 PM](https://user-images.githubusercontent.com/12800484/142696847-95b0abf7-b006-42fc-919f-8d69888c96ce.png)

**Comment by kaatvds** [comment]
need to keep terms of service and Privacy policy. Agreed, the rest can go!

**Comment by ellentohn** [comment]
I would leave our privacy policy and terms of service, the ohters an go
