### ISSUE TITLE
more info on indiv vendor page

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#78]
ISSUE 1230
Reported on Wed Jan 01 2020 17:51:03 GMT-0500 (EST)
Reported by Kaat Vander Straeten(KAATvds@gmail.com)
PRIORITY = Medium-High
STATUS =  - Submitted 

Site Url: https://community.massenergize.org/wayland/services/5

Description:
would be awesome to have the tel no, web address and email of the vendor on the indiv vendor page.

User Role: Community User
Notes: 3 but we have a work around

**Comment by Pongo1** [comment]
On the indiv vendors page already displays the name, picture, description, location of vendor, and all the services they provide. **Only if the admin provides them**, that is when they will be displayed

**Comment by kaatvds** [comment]
Fripong writes"On the indiv vendors page already displays the name, picture, description, location of vendor, and all the services they provide. Only if the admin provides them, that is when they will be displayed" That is not the case. I created all that info for "Vendor" on  Wayland, and none of it shows. In fact, the street address I put in was not retained in the Cadmin...

**Comment by kaatvds** [comment]
looks better but there are two emails: one for the business, one for the contact. 
We don't need the vendor contact - that's for Cadmins only. We only need
- business tell no
- web address
- business email 
![image](https://user-images.githubusercontent.com/30277868/78064867-64000900-7360-11ea-8a72-0a3215096b1b.png)

**Comment by kaatvds** [comment]
Not sure what would come under "More information"? Where on Cadmin side would that be input? If there is no place to input that please take that  off (best not to show "not provided" on a live site)

Also, it turns out there is no way to input vendor's website on cadmin side (so I just created ticket for Sam here #124 )

**Comment by Pongo1** [comment]
So More information was going to be for the website if provided, and any other information we might think of  in future.  The website urls are just not showing now because they are not in the API Sam sends through. When they are sent through, they will be displayed -- the code is there now. I have also prompted Sam

**Comment by kaatvds** [comment]
Sam says Frimpong needs to tie his Sam's changes to his so it shows the website

**Comment by ellentohn** [comment]
website address is not working, when you enter www.nytimes, it did not work

**Comment by ellentohn** [comment]
for info: delete "More Info" and just show www...... .com/org web site. 

Also space out the phone, vendor email and website, for website add web icon (little earth/globe)

**Comment by BradHN1** [comment]
Web site link is appended to the current url, so it doesn't work.
E-mail address should be a link to e-mail program to send e-mail.  
Phone number should link to making a call.

**Comment by BradHN1** [comment]
The phone number should link to making a phone call

**Comment by BradHN1** [comment]
@Pongo1 - one more issue here shows up in the compile:

Compiled with warnings.

./src/components/Pages/ServicesPage/OneServicePage.js
  Line 131:21:  The href attribute is required for an anchor to be keyboard accessible. Provide a valid, navigable address as the href value. If you cannot provide an href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid
