### ISSUE TITLE
Events: address repeats elements

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#789]
admin form:
![image](https://user-images.githubusercontent.com/30277868/145634349-bb4b6d40-4a6b-42cc-9eab-9c57d5673c8d.png)

on portal: 
![image](https://user-images.githubusercontent.com/30277868/145634463-509cd370-75ce-4235-a83d-835e1013739b.png)

**Comment by BradHN1** [comment]
@kaatvds 
I have fixed this, but the Unit number should come after the address, like this:

<img width="714" alt="Screen Shot 2021-12-16 at 12 04 48 PM" src="https://user-images.githubusercontent.com/12800484/146416537-b7a5c8ee-7afd-494e-8bc8-bcee219fe853.png">

In the case you showed, where you may want "Town Building Large Hearing Room" to come before "41 Cochituate Rd", you  would need to put that entire string in to address "Town Building Large Hearing Room, 41 Cochituate Rd".
