### ISSUE TITLE
on events can we have rsvp back?

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#80]
ISSUE 1246
Reported on Wed Jan 08 2020 23:22:31 GMT-0500 (EST)
Reported by Kaat Vander Straeten(KAATvds@gmail.com)
PRIORITY = Medium
STATUS =  - Submitted 

Site Url: https://community.massenergize.org/wayland/events/3

Description:
on events can we have rsvp back?

User Role: Community User

**Comment by frimpongopoku** [comment]
Unless a database model of the RSVP functionality exists that I dont know of, I will need things to be setup on the backend before I will be able to do this. So I will move it to backlog, and create a ticket on api for this functionality

**Comment by kaatvds** [comment]
RSVP is enabled on DEV on the profile but see ticket #335

**Comment by BradHN1** [comment]
This needs a bit of work, but functionality is there

**Comment by BradHN1** [comment]
Currently, the RSVP status is a blue pull-down button below each event card.  The blue doesn't look good, and the pull down should be integrated with the card, at the right side on the line with the even ttitle.
Also, if someone clicks the RSVP who doesn't have a profile, it should encourage them to create one where now it just doesn't function and gives no error.

**Comment by kaatvds** [comment]
Agree with Brad's comments
