### ISSUE TITLE
Events Calendar - view on all events page including events from other communities

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#806]
The all events page currently is event cards from your community

As a separate view, we want a calendar which can show events in your community by date, and optionally other communities, selected to be within a distance (10 miles, 25 miles, ) or all communities.

The calendar should be an off-the-shelf component if one suits the purpose.

Back-end changes will be needed (API Ticket [#413](https://github.com/massenergize/api/issues/413))

**Comment by frimpongopoku** [comment]
Noted @BradHN1

**Comment by BradHN1** [comment]
@frimpongopoku - there's a problem with the calendar in the case of a campaign or event with different start and end dates.  In this case we should just put the the start date on the calendar.  See image:
<img width="955" alt="Screen Shot 2022-02-02 at 5 30 25 AM" src="https://user-images.githubusercontent.com/12800484/152137611-8d1d8489-2170-48a5-8ed0-105ed886edbb.png">

**Comment by BradHN1** [comment]
@frimpongopoku - we've decided we want to eliminate the modal which comes up when you click on a calendar event, but just send to the event information page.  This modal: 
![Screen Shot 2022-02-10 at 10 03 25 AM](https://user-images.githubusercontent.com/12800484/153435416-39c976f2-ea63-42c7-a155-edecc9c2dd32.png)

**Comment by frimpongopoku** [comment]
Fixed a long time ago
