### ISSUE TITLE
Bug - Dev branch: Logged off users can't use the sign in link.

### ISSUE THREAD

**Issue by Davidjwkinghorn** [massenergize/frontend-portal#813]
Clicking sign in seems to reload the page, but doesn't take us to the sign in page. It seems to think I'm already logged in.

https://user-images.githubusercontent.com/15150372/149178100-40f0c483-021f-4595-9cab-c8b472a397c5.mov

**Comment by BradHN1** [comment]
@Davidjwkinghorn - I think this was probably fixed in the deployment I just did

**Comment by Davidjwkinghorn** [comment]
Yep, Just saw that!
