### ISSUE TITLE
Todo and Done dates dialog

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#826]
Kaat reports: Weird interactions tick box, drop down box and selection inside drop down: I tick the box for the household. The moment I click  in the dropdown that tick is taken  away, same with clicki on a choice. so whn I clikc submit" not added to to do

**Comment by dim505** [comment]
I was able to replicate this part "I tick the box for the household. The moment I click in the dropdown that tick is taken away" but when you select an option, the checkbox is ticked again.


I assume you don't want the checkbox to be unchecked when clicking on the dropdown?

**Comment by BradHN1** [comment]
Correct

**Comment by dim505** [comment]
pull request made
