### ISSUE TITLE
User submitted testimonial dialog - add close button

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#827]
After submitting testimonial, it is not clear how to get out of the dialog (click utside it, but that might nnot be clear): need a "close" button

**Comment by dim505** [comment]
pull  request made

**Comment by kaatvds** [comment]
Button looks very different from our other buttons and blends in with background. 
![image](https://user-images.githubusercontent.com/30277868/152586438-8b8eb3fb-e488-4191-8718-2c1227f4c02c.png)

**Comment by dim505** [comment]
I assume this ticket can be closed seeing that it made it to PROD?
@BradHN1

**Comment by BradHN1** [comment]
Yes, I think it is ok to close
