### ISSUE TITLE
Events normal view - keep cards the way they are in prod

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#835]

**Comment by kaatvds** [comment]
Can we also change "normal view" on first button into "upcoming" and center those two buttons
In calendar view change "back" too "previous".

**Comment by BradHN1** [comment]
Restored bottom-date-section to previous colors.  
Changed "normal view" to "upcoming", and "Back" to "Previous"
Didn't center the two buttons; don't know how and I think they are good aligned left.

The event card could use some shadowing to better define it, but that is beyond me at the moment
