### ISSUE TITLE
CAN Profile Icon Missing after Full Name changed.

### ISSUE THREAD

**Issue by Davidjwkinghorn** [massenergize/frontend-portal#841]
Changing full name overwrites the autogenerated user icon with a missing image and persists between logins

**Comment by Davidjwkinghorn** [comment]
Was this fixed? I'm still having this in the current Canary build. I also just discovered that changing your name also overwrites a user chosen profile icon with a missing image too, in a related issue.

**Comment by kaatvds** [comment]
It worked till I signed out and signed in under a diff user: the icon disappeared
https://github.com/massenergize/frontend-portal/issues/841
