### ISSUE TITLE
CAN User Chosen Icon Overwritten by Change to Profile Name

### ISSUE THREAD

**Issue by Davidjwkinghorn** [massenergize/frontend-portal#857]
Changing first, last, or preffered name overwrites user chosen icon with a missing image and persists between logins

**Comment by BradHN1** [comment]
I've already fixed this once, issue #841  - in EditingProfileForm.js.
The code around "body.profile_picture" should prevent this.  Can y

**Comment by Davidjwkinghorn** [comment]
I tested this separately. You fixed the overwriting of the autogenerated icon. I verified this earlier today. However if a user selects an image the same issue from before happens still, as of this morning. I'll look into it.

**Comment by Davidjwkinghorn** [comment]
`GET https://massenergize-files.s3.amazonaws.com/https%3A/massenergize-files.s3.amazonaws.com/media/Beatles_Bernie_Drum.jpg 403 (Forbidden)`
