### ISSUE TITLE
Alternate Method for Password Free Users to Delete Their Profiles

### ISSUE THREAD

**Issue by Davidjwkinghorn** [massenergize/frontend-portal#860]
Currently in Canary a user has to copy and paste a url from the email we send in order to delete their profile. This method is rather cumbersome. Due to the format of our emails (which we can't easily change), a user has to right click the link in their email in order to copy it.

**Comment by frimpongopoku** [comment]
When performing a task like deleting your profile, I think "cumbersome" is good 💀 🤣
