### ISSUE TITLE
Users Who Create a Profile with Password-Free Sign-in Should Be Able to Add Password Sign-in Method to Their Profile.

### ISSUE THREAD

**Issue by Davidjwkinghorn** [massenergize/frontend-portal#862]
Right now if a user creates a profile with the password sign-in method, they are able to add password-free sign in and may use both. However, if a user creates a profile with the password-free sign-in method, they cannot add the password sign-in method later. We should provide a way to do this. It is especially important for future admins until we add password-free sign-in for the admin portal. Currently if a password-free user was added as an admin there would be no way for them to log in without creating an entirely new profile with the password sign-in method.

**Comment by frimpongopoku** [comment]
When a password-less user adds a password, their account automatically
becomes an email/password account.

**Comment by BradHN1** [comment]
This may already be as requested, re-check.

**Comment by frimpongopoku** [comment]
@Davidjwkinghorn if your account is only using **ONLY** passwordless authentication, your menu will say "add password". If your account already has a password, it will say "change password". Maybe in your scenario, you had initially setup your account with passwordless, and later added a password, or the other way round -- that is why 🤔

**Comment by frimpongopoku** [comment]
@Davidjwkinghorn  this is not a bug, and things actually do work as you have described already.

**Comment by Davidjwkinghorn** [comment]
I'll move this back to `No Status` while I verify.

**Comment by Davidjwkinghorn** [comment]
I just created what should be a unique profile with Password-free auth and I'm seeing this.

![Image](https://user-images.githubusercontent.com/15150372/172904520-71126956-196a-4943-8664-8a93c9220515.png)

It's a brand new profile with no password authentication method.
