### ISSUE TITLE
Tour: several placement issues

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#867]
There are several placement issues. 

On second box (homepage) the cookie banner and the tour interfere with one another. Not sure how this can be addressed. Cookie banner first, THEN the tour??
![Screenshot (1393)](https://user-images.githubusercontent.com/30277868/153662209-ec84a105-716e-4cc4-9ac9-8797e7e4696a.png)

third box is not fully visible: make it pop up to the side of the card?
![Screenshot (1394)](https://user-images.githubusercontent.com/30277868/153662301-8f847570-bb47-4c35-a8a8-0e270fbe45e0.png)

when the tour returns to the homepage, the box was nowhere on the greyed-out screen - the cookie banner is also still messing with the screen.
![Screenshot (1395)](https://user-images.githubusercontent.com/30277868/153662351-fd15c2a5-b45d-4a87-9394-580c04c88982.png)

and the last one: box obscures the sign in button
![Screenshot (1396)](https://user-images.githubusercontent.com/30277868/153662406-07918dc2-361c-4401-a9ce-e3c9c6e388ba.png)

**Comment by BradHN1** [comment]
@frimpongopoku - I was testing the changes you made so far, look good.
For the last step (sign-in button), I found:
        placement: "left-end",
        offset: 100,

works pretty well.

**Comment by kaatvds** [comment]
in canary 4.1.34 and tour looks good!!! just one glitch: "These 4 buttons take you places. The one called "" will show you many good actions to take." I guess because that box is not called "Take action"
![Screenshot (1409)](https://user-images.githubusercontent.com/30277868/153918611-03625b48-7d36-4ed5-8eea-ae5e4e8d6829.png)
?

**Comment by BradHN1** [comment]
This is because none of the buttons on the demo site take you to the actions page.  That is not a normal case.
