### ISSUE TITLE
on Profile: when trying to add a team, error message

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#873]
error message and console:
![Screen Shot 2022-02-11 at 5 18 19 PM](https://user-images.githubusercontent.com/30277868/153681008-285d74f1-963e-437b-8e63-d853959066cf.jpg)
![Screen Shot 2022-02-11 at 5 17 33 PM](https://user-images.githubusercontent.com/30277868/153681009-14384401-86c6-485b-ae3a-4b7733ddda02.jpg)

**Comment by Davidjwkinghorn** [comment]
@BradHN1 or @kaatvds, has this happened since then?

**Comment by BradHN1** [comment]
I think this was fixed in February, but I suggest retesting it in Canary.
