### ISSUE TITLE
Sign in and get redirected to the wrong page

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#888]
Megan Sullivan observed that when signing in, she was directed to the All Actions page rather than the home page.  Not sure why but it was confusing.  

In AppRouter.js, code in saveCurrenTPageURL which saves the page last_visited is presumably causing this confusion.  It may be something that standard users rarely see, and new users never see.

**Comment by Davidjwkinghorn** [comment]
Not currently applicable.
