### ISSUE TITLE
Registration page improvements

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#889]
Discussing with Megan Sullivan, we think the registration form needs to be simplified further, to be more inviting for new users.  Less questions, more inviting.

Currently it says: **Almost there, please tell us all of the following. Thank you!**  which seems friendly but isn't because it doesn't tell you why it needs the info.  
That text should be customizable, with a graphic (default or cadmin supplied).

Change "Preferred Name (visible on website)" to "User Name (unique)"
possible link to autogenerate User Name from First and Last name
Remove City/Town and State fields
Keep ZIP code with explanation why it's needed

**Comment by kaatvds** [comment]
The following are probably already tickets but am parking them here: 
question: When signing up I get mail with verif link > click on it > take me to little box that says "we have verified your email, continue" > press continue, and I have to sign in AGAIN.  (*) SHOULD detect this came from an account completion link and send straight to the account completion form.

(*) there are also  problems with that form/modal? not scrlable unless I minnimize screen: In this screeshot I can't scroll down to the bottom to click o the button to continue:
![Image](https://user-images.githubusercontent.com/30277868/172897365-8eaa6b66-f1fe-4c53-ba96-657d655a30ff.png)

**Comment by kaatvds** [comment]
suggestions for that page - no details yet on autogenerate, etc.

![Image](https://user-images.githubusercontent.com/30277868/173095612-5e10b926-a544-4471-bb8b-edffc4a37d4c.png)

**Comment by BradHN1** [comment]
Pretty good!  

I don’t like “Nickname”.  I prefer “Username"


I might suggest shortening text by removing the sentence “We ask for your full name because…”.  
Also a tweak:
"Your home zip code is used to make your actions count towards … collective goal.”

don’t need to get into double counting.

**Comment by kaatvds** [comment]
updated design w Brad's comments:
![Registration completion form (1)](https://user-images.githubusercontent.com/30277868/173397871-c68eebd5-92b7-40f6-a97f-f8fe719c0491.png)
