### ISSUE TITLE
User submitted Actions, Events and Vendors ("Service Provider")

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#892]
Like user submitted testimonials, we'll have a simllar button on the filter bar which brings up a modal form to fill out.
In each case the API route is actions.add, events.add, vendors.add

The information in each case is slightly different:

Action fields:
tltle ("Action Name")
featured_summary ("Description")
steps_to_take ("Action steps")
image

Event fields:
title
date
time
location
description

Vendor fields:
name 
phone_number 
email 
description 
address 
website
    key_contact 
  logo (image)

**Comment by Davidjwkinghorn** [comment]
[Issue 586](https://github.com/massenergize/frontend-admin/issues/586) is a prerequisite to this issue.

**Comment by BradHN1** [comment]
Testing in dev: The create action form has the wrong fields:
<img width="1055" alt="Screenshot 2023-04-19 at 7 22 24 PM" src="https://user-images.githubusercontent.com/12800484/233220484-26a83c32-2795-4e37-8009-3f8aa502b112.png">

It asks "which action this testimonial is about" and a bunch of things relating to testimonials.
Fields should be Title, Featured Summary, Steps to Take, Deep Dive, and Image

**Comment by BradHN1** [comment]
User Submitted Events - the input form was ok.
I entered a location for the event, and that was not saved on the back-end
I specified the time as 10:30am (meaning local time on east coast) and the time was either saved incorrectly, or comes out off by 4 hours on the Admin:
<img width="357" alt="Screenshot 2023-04-19 at 7 34 48 PM" src="https://user-images.githubusercontent.com/12800484/233222021-054feb5d-f236-47ce-a9b4-ce4150b61589.png">

**Comment by BradHN1** [comment]
Also - on the user submitted event, it should be marked on the ftont-end as "Draft - pending approval"
On the one event view, it should have an edit button for the user who submitted it:
<img width="1064" alt="Screenshot 2023-04-19 at 7 31 35 PM" src="https://user-images.githubusercontent.com/12800484/233222178-5c67a9c5-e226-4efa-a05a-50c85c39a0e4.png">

**Comment by BradHN1** [comment]
Usher submitted service providers - the input form looks ok.
When submitted , the form hangs with a console error:
<img width="1495" alt="Screenshot 2023-04-19 at 7 46 38 PM" src="https://user-images.githubusercontent.com/12800484/233223076-e81349e8-be1f-4906-bd19-7b917828754c.png">
