### ISSUE TITLE
Contact-us page cosmetic improvement

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#900]
Fix text formatting.

**Comment by BradHN1** [comment]
Text is bunched together:
![Screen Shot 2022-05-18 at 10 23 11 AM](https://user-images.githubusercontent.com/12800484/169066951-fee08d00-1b02-41d9-a35a-ac46f8b3f262.png)

If Location not specified (as in JCAN), leave out "Location"

Change "site admin" to "Community Administrator"

Add profile pic next to Community admin name, if profile pic was saved

Leave out "Here" above the contact community admin form.

**Comment by BradHN1** [comment]
Four slight tweaks requested from Mobile testing:

1. Don't include "Location" if no location specified:
![Screen Shot 2022-05-27 at 5 37 27 AM](https://user-images.githubusercontent.com/12800484/170673899-442e8693-dd64-4dcf-82ed-4b94eb16cdb0.png)

2. If the location includes just a state, don't include the comma ',':
![Screen Shot 2022-05-27 at 5 35 41 AM](https://user-images.githubusercontent.com/12800484/170674041-78def244-0882-4d9f-a29b-e36ffa756339.png)

3. Improve the spacing, and perhaps add a small, light grey divider line between the location and the Contact Community Admin form.  Note that the Community Admin is spaced differently than the Location, which looks odd:
![Screen Shot 2022-05-27 at 5 27 15 AM](https://user-images.githubusercontent.com/12800484/170674636-b11d5d89-302e-4b70-a401-aee809269785.png)

**Comment by BradHN1** [comment]
Looks good with the profile pic:
<img width="412" alt="Screen Shot 2022-05-27 at 5 53 44 AM" src="https://user-images.githubusercontent.com/12800484/170676647-f5d82a71-ccb2-46e8-869d-f6544c6fef6a.png">

**Comment by abdullai-t** [comment]
only for mobile ?

**Comment by BradHN1** [comment]
No, that is just where I'm testing.  The comments apply to both laptop and mobile.

**Comment by abdullai-t** [comment]
sure
