### ISSUE TITLE
CAN: RSVP button not showing on event card in all events

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#904]
RSVP is enabled. When clicking through the button does show on the indiv event page.
![image](https://user-images.githubusercontent.com/30277868/159025957-ad50b8f7-197c-4f87-9927-73c9135fbe0a.png)

**Comment by kaatvds** [comment]
and when I click on RSVP it doesn't tell me I have RSVP-ed: just changes back to initial RSVP button
![image](https://user-images.githubusercontent.com/30277868/159026228-393aae99-05fd-4a02-b53e-c8c842e08530.png)

**Comment by BradHN1** [comment]
In that case the event was in the past., which is why the RSVP button doesn't show up.

FIxed an issue with RSVPs which caused the second error.
