### ISSUE TITLE
Admin: Sandbox

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#932]
When clicking back  button in sandbox you leave sandbox and get the "this community doesn't exist" page. 
Very annoying for admin trainers, admin trainees, admins and organizers demoing their site-in-the-making to mayors :(

**Comment by frimpongopoku** [comment]
Can I get more context on this ticket? Cos I did try this and when I click back, it works fine.
See: 

https://user-images.githubusercontent.com/26961591/172118071-5c7df42f-a7ac-4669-929e-32e35d1acf9c.mov

**Comment by frimpongopoku** [comment]
What needs to be done (Just notes): 

1. Keep user in sandbox mode after refresh 
2. Add some form of indication on the interface to always tell the user that they are in the sandbox

**Comment by BradHN1** [comment]
Working in Canary
