### ISSUE TITLE
Cookie banner needs formatting on mobile

### ISSUE THREAD

**Issue by Davidjwkinghorn** [massenergize/frontend-portal#936]
On my phone the cookie banner takes up almost half my screen. I'm not sure what form it should take on mobile devices, maybe just centering the button and the text would be enough.

![Screenshot_20220419-102550_Chrome](https://user-images.githubusercontent.com/15150372/164028172-144541bb-5b43-44e6-bb04-e2a39b7f5d71.jpg)

**Comment by frimpongopoku** [comment]
That can be a good thing.... 🌚  Cos we need users to pay attention to it and get it over with .... 🤣 🤣

**Comment by BradHN1** [comment]
I think we should make this simpler still, like the following:
<img width="835" alt="Screen Shot 2022-05-04 at 5 57 05 AM" src="https://user-images.githubusercontent.com/12800484/166744891-781bdcfa-1bba-40bc-b3d6-174ac61417af.png">
