### ISSUE TITLE
All actions page - Guest sign in dialog doesn't show up without scrolling

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#938]
For actions beyond the first couple, the 'guest sign in dialog was hiddne so it didn't appear to work.
![IMG_F0FDEE14801E-1](https://user-images.githubusercontent.com/12800484/164058038-5c5f32e5-f90d-4f85-a451-29e068d50d0e.jpeg)

**Comment by Davidjwkinghorn** [comment]
Was able to reproduce this on my Android device. If you scroll down on any page before the sign in dialogue pops up you have to scroll back up to the top to see it.

**Comment by BradHN1** [comment]
Identical to issue #934
