### ISSUE TITLE
Make the button to leave a testimonial at the top of the page visible on mobile.

### ISSUE THREAD

**Issue by Davidjwkinghorn** [massenergize/frontend-portal#941]
The only way to leave a testimonial on mobile is to scroll all the way to the bottom.

**Comment by BradHN1** [comment]
HorizontalFilterBox should have same functionality on Mobile as on Laptop.
Search should be inside the filter bar, not on separate line which takes up way too much space.
For Testimonials, "Add Testimonial" button should be in the box.  Format of that button could use improvement.

**Comment by frimpongopoku** [comment]
Which one of the buttons? And what kind of improvements do you recommend? They all look fine to me.
