### ISSUE TITLE
guest user email validation is broken

### ISSUE THREAD

**Issue by Davidjwkinghorn** [massenergize/frontend-portal#942]
I have been unable to sign in as a guest recently. Both with real email addresses and made up ones. The errors all said I already have a profile with those addresses, though I was making them up on the spot and hadn't used them before.

![Screenshot_20220419-171248_Chrome](https://user-images.githubusercontent.com/15150372/164104025-01335350-17c1-4bca-83ca-fe0dc2a0d1a9.jpg)

Then I got this strange error.
![Screenshot_20220419-171657_Chrome](https://user-images.githubusercontent.com/15150372/164104078-711a7dec-e438-41c6-88bd-cb5844a6d005.jpg)

**Comment by BradHN1** [comment]
This was due to something I was testing and forgot to back out.
