### ISSUE TITLE
Change wording in sign in with email and PW

### ISSUE THREAD

**Issue by apowelka** [massenergize/frontend-portal#954]
Change wording from:
Welcome!
Fill in the form appropriately to activate the 'sign in' button

to:
Welcome!

![image](https://user-images.githubusercontent.com/60662056/165547862-88d29712-369c-49ef-99cd-187615b98179.png)

**Comment by kaatvds** [comment]
![Image](https://user-images.githubusercontent.com/30277868/172895508-9a96636a-7414-4046-8d5d-e7a96fec2793.png)
