### ISSUE TITLE
PROD - can't sign is as guest on Iphone with Safari

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#961]
I am trying to sign on as a guest user with my ipnone, and it isn't working.  My email is accepted and it says I can continue, but then it doesnt't sign me in.  

I can sign in on the laptop, with safari or chrome. On the laptop, simulating the mobile in crhome I can sign in.  I dont know how to do that in Safari.

Just updated my phone operating system yesterday to 15.4.1 - could this be causing the problem?

**Comment by Davidjwkinghorn** [comment]
Is this issue related to cookies on Safari possibly?
