### ISSUE TITLE
html code displayed in  some  testimonials

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#963]
suresh reports: Please see the “Testimonial” tab on the Solar Action. There are leading format marks. I tried to play with fonts while editing the Testimonial but it does not allow me to set the font to “System Font” and<p> format mark always appears as noted on other  “Testimonial” tabs on other Actions. Do you know what is the “System Font”?
<img width="834" alt="Screen Shot 2022-05-03 at 9 59 44 AM" src="https://user-images.githubusercontent.com/30277868/166574016-37382fe8-ed66-4a98-8503-2d49cb825f05.png">

**Comment by BradHN1** [comment]
The problem is in MiniTestimonial.js, which doesn't display the text as HTML. 
Challenge is that the short preview with "Read More..." tends to end within an HTML block.

Options:
strip out the HTML tags and &nbsp junk, just display text;
eliminate the test, just leave the title
scroll the HTML text within that section.

**Comment by kaatvds** [comment]
Would love to see this addressed. Several communities are pushing hard on getting testimonials.

**Comment by frimpongopoku** [comment]
@BradHN1  that is a good idea, but stripping the HTML will not be that simple. That is why when I was implementing this HTML view / Read more feature for testimonial on the main testimonial page cards, I never touched the real content itself. On  those cards I actually do display the whole HTML content, but then shrink shrink the height of the height, depending on whether or not the user is in "Read More" mode. Maybe @dim505  could do the same here as well 🤔

**Comment by BradHN1** [comment]
Thanks @frimpongopoku.
@dim505 - please use StorySheet.js lines 173-291 as the example of how to implement this.

**Comment by dim505** [comment]
Any updates? I made a pull request
