### ISSUE TITLE
Remove the bottom part of footer: "Made with ... by "

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#969]
As sweet as it is, let's eliminate the bottom section of the footer. 

Put the version number where the "Donate Now" link is, which can be removed

Update copyright to 2022.

<img width="829" alt="Screen Shot 2022-05-10 at 3 52 33 PM" src="https://user-images.githubusercontent.com/12800484/167710927-fa30aeb1-91fb-4a2c-b6c1-889ba2f8156c.png">

**Comment by dim505** [comment]
What is the version number? I assume its Prod-4.2.17 ?

**Comment by BradHN1** [comment]
Just the numeric part.

**Comment by dim505** [comment]
@BradHN1 can this be closed out?
