### ISSUE TITLE
When setting action as Done, don't ask which household if only one household.

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#97]
Currently when an action is "Done" the user is asked which household it applies to.  A reasonable question if there are more than one household but annoying for one household, the usual case.  So avoid this and the additional "Submit" required which some people miss.

**Comment by kaatvds** [comment]
This fix broke the TO do list cf. new issue #145

**Comment by kaatvds** [comment]
Which is now a critical issue
